#594/Scenario moveTest tests and mocks
jac-uk/admin pull request #1060
Opened 2020-11-10 12:22 UTC by tomlovesgithub

Its going to worth adding to the test suite created here for the other QT types and spending some time documenting the how we expect this stuff to work, so that tests can be added to.

2020-11-11 11:44 UTC, warrensearle reviewed
This is looking good. I think `moveTest` does the same for all test types so we shouldn't need to repeat the tests for each type

2020-11-13 13:03 UTC, lloback requested changes

2020-11-13 13:03 UTC, lloback commented on src/store/qualifyingTest/qualifyingTestResponses.js
>        await context.dispatch('update', { data: data, id: qualifyingTestResponse.id });
@mbrookeswebdev are you sure that removing this will continue to work backwardly-compatible? What steps did you take to test this?

2020-11-13 13:05 UTC, mbrookeswebdev commented on src/store/qualifyingTest/qualifyingTestResponses.js
>        await context.dispatch('update', { data: data, id: qualifyingTestResponse.id });
@lloback I think you meant to tag @tomlovesgithub

2020-11-13 16:37 UTC, tomlovesgithub commented on src/store/qualifyingTest/qualifyingTestResponses.js
>        await context.dispatch('update', { data: data, id: qualifyingTestResponse.id });
https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/594#issuecomment-724053152
tests have been added, removing the block was part of the requirements

2020-11-14 10:34 UTC, lloback approved these changes

2020-11-16 14:07 UTC, warrensearle approved these changes
👍

2020-11-16 14:45 UTC, merged