Feature/960 upload Assessment on Behalf of the assessor
jac-uk/admin pull request #1062
Opened 2020-11-11 10:33 UTC by lloback

This functionality allows the admns to upload a file on behalf of the assessor.

2020-11-11 12:54 UTC, mbrookeswebdev approved these changes

2020-11-11 13:49 UTC, tomlovesgithub approved these changes

2020-11-11 13:50 UTC, warrensearle requested changes
This is looking good however I think we need to improve the data model. Previously only Assessors uploaded assessments and we used their `AssessorId` in the storage path for where the file is saved. Now that admin can upload an assessment on behalf of the assessor we don't (necessarily) have the `AssessorId` and we shouldn't populate this with the Admin user's UID instead - unless we are clear that's what we've done and even then it feels wrong.

Perhaps we should store the explicit storage path in the assessment document itself.

2020-11-12 21:05 UTC, lloback commented
> This is looking good however I think we need to improve the data model. Previously only Assessors uploaded assessments and we used their `AssessorId` in the storage path for where the file is saved. Now that admin can upload an assessment on behalf of the assessor we don't (necessarily) have the `AssessorId` and we shouldn't populate this with the Admin user's UID instead - unless we are clear that's what we've done and even then it feels wrong.
> 
> Perhaps we should store the explicit storage path in the assessment document itself.

This is done.

2020-11-13 15:56 UTC, warrensearle approved these changes
This works well 👍

2020-11-14 10:34 UTC, merged