Feature/1058 reset button for qts
jac-uk/admin pull request #1068
Opened 2020-11-16 15:23 UTC by mbrookeswebdev

2020-11-16 16:20 UTC, lloback approved these changes

2020-11-16 16:49 UTC, warrensearle requested changes
This looks good. Could you amend so the Reset button only shows for the `authorisedToReset` users, for now?

2020-11-16 17:51 UTC, mbrookeswebdev commented
> This looks good. Could you amend so the Reset button only shows for the `authorisedToReset` users, for now?

@warrensearle done!

2020-11-17 07:27 UTC, lloback approved these changes

2020-11-17 07:28 UTC, merged