#1026 Add checkbox and role summary for Welsh posts
jac-uk/admin pull request #1072
Opened 2020-11-19 10:53 UTC by mbrookeswebdev

2020-11-19 15:34 UTC, warrensearle requested changes
Need to include data on the Show page too 👎

2020-11-19 18:07 UTC, mbrookeswebdev commented
> Need to include data on the Show page too 👎

@warrensearle done :)

2020-11-19 18:27 UTC, warrensearle requested changes
See comment.

2020-11-19 18:27 UTC, warrensearle commented on src/views/Exercises/Show/Summary.vue
> +    areThereWelshPosts() {
Ooh we have a filter for this.
In the template you can do
```
{{ exercise.welshPosts | toYesNo }}
```

2020-11-20 08:35 UTC, mbrookeswebdev commented on src/views/Exercises/Show/Summary.vue
> +    areThereWelshPosts() {
@warrensearle sorted

2020-11-20 09:21 UTC, warrensearle approved these changes
Marvellous 👍

2020-11-20 16:46 UTC, merged