account for missing info in applications
jac-uk/admin pull request #1190
Opened 2021-02-24 19:02 UTC by tomlovesgithub

2021-03-04 11:23 UTC, warrensearle requested changes
Please see comments

2021-03-04 11:23 UTC, warrensearle commented on src/views/Exercises/Applications/Application.vue
> +                v-if="application.equalityAndDiversitySurvey && Object.keys(application.equalityAndDiversitySurvey).length"
It would be nice to simplify / minimise the amount of Javascript code within the template.

I wonder if there's a _simpler_ way to check what you need or perhaps use `computed` variable (without ending up with loads) or a helper method.

2021-03-04 11:23 UTC, warrensearle commented on src/views/Exercises/Applications/Application.vue
> +                Explain how you've gained experience in law.
The UI for this has gone a bit skew-wiff 
<img width="793" alt="Screenshot 2021-03-04 at 11 06 29" src="https://user-images.githubusercontent.com/8524401/109956596-bb7ac780-7cdb-11eb-8a39-ee8d6d534a83.png">
Plus see that Memberships shows up when it's empty: so either needs text to explain or to be hidden

2021-03-09 11:14 UTC, HalcyonJAC commented
spotted a typo - `experience` is spelt wrong in this code block:

```
<div
    v-if="application.expereience && application.expereience.length"
>
```

`\src\views\Exercises\Applications\Application.vue`

2021-03-11 09:53 UTC, warrensearle commented on src/views/Exercises/Applications/Application.vue
> +                Explain how you've gained experience in law.
@tomlovesgithub Memberships still shows up when there's no data for it. Perhaps create a specific bug ticket to address this if you prefer.

2021-03-11 09:57 UTC, warrensearle approved these changes
Code looks ok - there's still room to simplify the template however no show-stoppers. 👍 
(oh I feel mean 😄)

2021-03-11 10:42 UTC, tomlovesgithub commented
Thank you Warren, very merciful  - I will return to slay the `applications.vue` one day

2021-03-11 10:43 UTC, merged