Feature/1206 enable new and old character info on candidate page
jac-uk/admin pull request #1222
Opened 2021-03-18 15:38 UTC by mbrookeswebdev

The candidate's view (Applications > (any applicant) > Full information > Candidate) now shows correct Character Info information like all other views on Apply and Admin - dependant on what version of Character Information form was used.

I also made margins smaller, so the form looks in line with other parts of Admin and Apply.

![CharInfo](https://user-images.githubusercontent.com/40855898/111653508-e39c1780-87ff-11eb-8c99-5a2455441ce9.png)

2021-03-22 09:51 UTC, warrensearle requested changes

2021-03-22 09:51 UTC, warrensearle commented on src/views/Candidates/CandidatesView.vue
> +    getApplicationVersion() {
I think we could use a `_versionNumber` in the `characterInformation` documents to simplify this. Rather than looking at the exercise (if we have selected an exercise).
The version number would be set via Apply so a small/simple change would be needed there.

2021-03-22 14:31 UTC, mbrookeswebdev commented on src/views/Candidates/CandidatesView.vue
> +    getApplicationVersion() {
I've added _versionNumber to Candidate. It shouldn't be an issue, because I don't think anyone applied yet using the new form.

2021-03-23 15:32 UTC, warrensearle approved these changes
👍

2021-03-25 14:41 UTC, merged