qt statusLog reset field and modal
jac-uk/admin pull request #1227
Opened 2021-03-22 13:19 UTC by tomlovesgithub

2021-04-06 10:06 UTC, HalcyonJAC reviewed
I am not sure whether the JAC admin portal is used on mobile phones or not, but the modal popup is not mobile-friendly

![image](https://user-images.githubusercontent.com/79906532/113694689-f9e31800-96c7-11eb-8d42-2a1c29230d72.png)

2021-04-06 10:06 UTC, HalcyonJAC commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> +              Reseting this candidates test will overwrite their
`candidates` should be `candidate's` ;)

2021-04-06 10:14 UTC, HalcyonJAC commented
It would appear that the code in file `helpers\authUsers.js` is related to identifying system adminitrators. For reference, here is the code contained in the `helpers\authUsers.js` file:

```js
const authorisedUsers = [
  'maria.brookes@judicialappointments.digital',
  'warren.searle@judicialappointments.digital',
  'tom.russell@judicialappointments.digital',
  'kate.malone@judicialappointments.digital',
  'joy.adeagbo@judicialappointments.digital',
];

const authorisedToPerformAction = async (email) => {
  return authorisedUsers.includes(email);
};

export {
  authorisedToPerformAction
};
```

Consider refactoring the code above as follows:

- Rename the file to `helpers\sysAdmins.js`
- Rename `authorisedUsers` to `sysAdmins`;
- Rename `authorisedToPerformAction()` to `isSysAdmin()`

2021-04-20 15:04 UTC, mbrookeswebdev commented
As per comment above re: authUsers.js - as soon as we'll implement user roles (hopefully soon!), we won't need this file.

2021-04-20 15:32 UTC, mbrookeswebdev approved these changes
I've tested it and it works.

2021-06-30 10:56 UTC, KateMJAC commented
Ticket to be discussed at Friday stand-up on 2 July. Advised by Tom that we have the option to proceed with this work or roll what has been done back. 

We need consensus as to the value of the work and whether its felt we should proceed.

2021-07-08 09:56 UTC, HalcyonJAC commented
Hi @tomlovesgithub please could you provide some info on how to test? Thanks!

2021-07-08 15:43 UTC, tomlovesgithub commented
> Hi @tomlovesgithub please could you provide some info on how to test? Thanks!

@HalcyonJAC 
Apologies! 
Added some directions for testing.

2021-07-18 15:14 UTC, londonprojects commented
@tomlovesgithub Is this ready for testing?

2021-07-20 15:26 UTC, mbrookeswebdev approved these changes
👍

2021-07-21 15:03 UTC, HalcyonJAC approved these changes

2021-07-22 09:03 UTC, warrensearle requested changes
All looks good just there appears to be a lot of boilerplate styling for the `Modal`. Please check if it's all needed... if it is then we should create a new ticket to refine the Modal component so it's more streamlined/easier to use.

2021-07-22 10:39 UTC, tomlovesgithub commented on src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> +  }
I think some of the code was trialed before rolling out to the kit. Should still work without it, and ive submitted some changes to the jac-kit so the work isnt lost.

2021-07-22 11:01 UTC, warrensearle approved these changes

2021-07-22 15:28 UTC, joy-ade reviewed
Out to UTG 22/7/2021

2021-07-23 11:17 UTC, joy-ade approved these changes
Approved by product team and UTG

2021-07-23 11:17 UTC, merged