Feature/1077 Display responses provided in a previous test#1077
jac-uk/admin pull request #1259
Opened 2021-04-12 11:59 UTC by lloback

This PR fixes this issue, by showing the questions and answers all the time (if they present), even if the test is not completed.

2021-04-12 13:01 UTC, mbrookeswebdev submitted a review, later dismissed
I've checked out the branch and it seems to work as expected, see screenshot below:
![QTTest](https://user-images.githubusercontent.com/40855898/114398343-98272000-9b97-11eb-9621-17844e715d2c.png)

2021-04-12 13:12 UTC, mbrookeswebdev reviewed
I saw this in the console after moving to a mop up a candidate who started the test but didn't provide any answers yet.

![Screenshot 2021-04-12 at 14 06 51](https://user-images.githubusercontent.com/40855898/114399451-d709a580-9b98-11eb-8b8e-005d5899aebb.png)

2021-04-12 23:16 UTC, lloback commented
@mbrookeswebdev I can't reproduce that.

2021-04-14 14:22 UTC, HalcyonJAC requested changes

2021-04-14 14:22 UTC, HalcyonJAC commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> +      return this.response ? true : false;
Hi @mbrookeswebdev 

From what I can tell, `hasStarted()` will always return `true` now as `this.response` will never be `null`. The only exception would be if the `responseId` in the URL didn't point to a valid `qualifyingTestResponse` document in Firestore which I can't see happening.

The only place that hasStarted() is used is this code block below:

```js
    <div v-if="hasStarted">
        <TabsList
          :tabs="tabs"
          :active-tab.sync="activeTab"
    />
```

Perhaps remove it from the above code block then delete the `hasStarted()` function from this component?

2021-05-04 07:59 UTC, lloback commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> +      return this.response ? true : false;
I think we should leave for backward compatibility. There will be some test without it and we don't want to throw an error.

2021-05-04 08:17 UTC, lloback commented
@mbrookeswebdev I can't reproduce the issue you mentioned. Please provide a direct link to the page, so I can check. Thanks.

2021-05-04 10:23 UTC, mbrookeswebdev commented
> @mbrookeswebdev I can't reproduce the issue you mentioned. Please provide a direct link to the page, so I can check. Thanks.

@lloback I can't reproduce this error now either, so maybe a glitch of some sort.

2021-05-04 10:27 UTC, lloback commented
@mbrookeswebdev check if you need anything else from this PR. Let's move the ticket!

2021-05-04 10:38 UTC, mbrookeswebdev approved these changes

2021-05-06 09:16 UTC, warrensearle approved these changes
Looks good to me. 👍

2021-05-06 09:37 UTC, warrensearle commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> +      return this.response ? true : false;
Good spot @HalcyonJAC! Perhaps `hasStarted` is briefly relevant while the view loads as `this.response` will be null until the record has loaded.... so I'm ok with leaving it there for now or using `v-if="response"` instead of `v-if="hasStarted"`

2021-05-07 15:45 UTC, tomlovesgithub commented
works for me 👍

2021-05-10 13:47 UTC, lloback commented
@KateMJAC let me know your thoughts.

2021-05-18 14:27 UTC, KateMJAC commented
@lloback I wasn't able to reproduce. I can see your example using https://jac-admin-develop--pr1259-feature-1077-display-7jlvq929.web.app/exercises/wdpALbyICL7ZxxN5AQt8/tasks/qualifying-tests/JTx6phqRwUJwroLgkBgR/response/Ls2eoLaM56Lgg1RrXFJb/ 

But was unable to see answers for those I transfered to a mop up myslef.

2021-05-18 14:46 UTC, lloback commented
> But was unable to see answers for those I transfered to a mop up myslef.

Hi @KateMJAC , can you please post the link here of the ones you transferred and did not see the results? Let me investigate.

2021-05-19 14:11 UTC, KateMJAC commented
@lloback the link is: https://jac-admin-develop--pr1259-feature-1077-display-7jlvq929.web.app/exercises/7NEtYLJiv7bels10ANKT/tasks/qualifying-tests/QodQ79B6aRTJXwKh57Pe/response/tDgLOzxuiiZRKtze0ZT5/  

Maybe I have done something wrong, but it seems like a simple process.

2021-05-24 06:27 UTC, lloback commented
> @lloback the link is: https://jac-admin-develop--pr1259-feature-1077-display-7jlvq929.web.app/exercises/7NEtYLJiv7bels10ANKT/tasks/qualifying-tests/QodQ79B6aRTJXwKh57Pe/response/tDgLOzxuiiZRKtze0ZT5/
> 
> Maybe I have done something wrong, but it seems like a simple process.

PLease check this link again, @KateMJAC . Regards.

2021-06-16 18:31 UTC, lloback commented
@KateMJAC do you need anything else from me on this ticket? This is ready to approve and merge.

2021-06-22 07:01 UTC, lloback commented
@KateMJAC and @joy-ade Please check this functionality.

2021-06-23 10:45 UTC, KateMJAC commented
This ticket has been sent to the UTG. We can't merge until we et positive feedback. Update to follow.

2021-06-23 11:15 UTC, KateMJAC commented
@lloback this needs to go to the UTG for positive testing before it can be merged. 

The PR review needs to be re-generated to provide it to the UTG. 

Tom attempted to regenrate it but an error message flagged. 

@joy-ade FYI

2021-06-25 22:34 UTC, lloback commented
We need to generate a new URL for testing. Closing this PR and opening a new one

2021-06-25 22:34 UTC, closed without merging