admin#1203 Ability to copy a QT test
jac-uk/admin pull request #1276
Opened 2021-04-20 01:09 UTC by lloback

**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---

## What's included?
This PR adds a button to allow:
1.  the copy of a QT test to the clipboard
2. the paste of the clipboard when creating a new QT test

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
1. Go to any QT test, and a button "Copy QT to clipboard"
> when clicked, it will show as copying and then the success message will show up

2. On the QT list, a button with the text "Create new from clipboard" is showing up
> Paste the content of the clipboard and follow the instructions

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

2021-04-21 15:55 UTC, mbrookeswebdev commented
I've tested creating the new QTs, it looks like it works well, but I've managed to squeeze out this small error into console a few times, but not sure why/it happens other that I click on Copy QT button, sometimes it errors, sometime it doesn't.

![screenshot](https://user-images.githubusercontent.com/40855898/115582840-3e260900-a2c1-11eb-8228-91b0a27a1753.png)

![screenshot2](https://user-images.githubusercontent.com/40855898/115583466-d1f7d500-a2c1-11eb-963d-1aaf78f59bfb.png)

2021-04-21 17:03 UTC, lloback commented
@mbrookeswebdev please share the link of the specific place where you found this issue. I can't reproduce it, but I am willing to look at it. The `innerText` is used to replace the text of the button after you clicked on it. it is using a VUE ref, so I think it is present and shouldn't be undefined - unless you click on it before the page and the script fully loads. Let me know.

2021-04-21 17:43 UTC, mbrookeswebdev commented
@lloback yes as I mentioned, this issue appears intermittently. For example, I've created the QT and landed [on this page](https://jac-admin-develop--pr1276-feature-1203-copy-qt-h60ejwff.web.app/exercises/EzC6vKO8kaBduxSq7nLB/tasks/qualifying-tests/6erHDwn7gZ8t04ydKiKh/) and then after I've clicked 'Copy QT to Clipboard' and then 'Review', I've arrived [to this page](https://jac-admin-develop--pr1276-feature-1203-copy-qt-h60ejwff.web.app/exercises/EzC6vKO8kaBduxSq7nLB/tasks/qualifying-tests/6erHDwn7gZ8t04ydKiKh/review) and error showed up.

2021-04-22 14:40 UTC, HalcyonJAC commented
This is another ticket in the review lane right now called [#1244 - Equal Merit Zone Tie-break Tests](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1244) which adds the ability to create tie-breaker tests. I implemented it by re-using existing QT components. If we want to be able to create copies of tie-breaker tests too, the folllowing code would need adding: 

- A new `equal-merit-tie-breakers/new-from-clipboard` route will need adding 
- `QualifyingTestNewFromClipboard` component will need tweaking to consider the value of the `isTieBreaker` prop that is passed in through the router

2021-04-26 00:00 UTC, warrensearle requested changes
A few tweaks needed. See comments. 😄

2021-05-04 08:31 UTC, lloback commented on src/router.js
> +import QualifyingTestNewFromClipboard from '@/views/Exercises/Tasks/QualifyingTests/QualifyingTest/NewFromClipboard';
The new route's route is cleaner, because we are actually creating a new test by passing the "CREATE NEW" route. Let me know what you think  @warrensearle

2021-05-04 12:47 UTC, KateMJAC reviewed
This tested sucessfully for me. This needs to go to the user testing group and suggestion from Warren implemented, before we can deploy. 

I will update with UTG results.

2021-05-04 21:44 UTC, lloback commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
> +      delete clipboardQT.vacancy;
this is done.

2021-05-04 21:47 UTC, lloback commented on src/views/Exercises/Tasks/QualifyingTests/Cover.vue
> +      v-if="exercise.exercisePhoneNumber && exercise.emailSignatureName"
this is the standard things that you need before creating a test. this was copied from the button CREATE NEW and it should be here.

2021-05-04 21:47 UTC, lloback commented on src/router.js
> +import QualifyingTestNewFromClipboard from '@/views/Exercises/Tasks/QualifyingTests/QualifyingTest/NewFromClipboard';
no changes made.

2021-05-04 21:52 UTC, lloback commented
@warrensearle this is ready to review again.

2021-05-05 10:56 UTC, KateMJAC reviewed
This PR has been successfully tested by the UTG.

2021-05-05 13:23 UTC, warrensearle approved these changes
Great, thanks @lloback 👍

2021-05-05 18:40 UTC, lloback commented
@tomlovesgithub @mbrookeswebdev pls review.

2021-05-06 07:49 UTC, mbrookeswebdev approved these changes

2021-05-09 23:03 UTC, lloback commented
> There is another ticket in the review lane right now called [#1244 - Equal Merit Zone Tie-break Tests](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1244) which adds the ability to create tie-breaker tests. I implemented it by re-using existing QT components. If we want to be able to create copies of tie-breaker tests too, the folllowing changes would need to be made to this PR once the tie-breaker code has been merged into `develop`:
> 
> * A new `equal-merit-tie-breakers/new-from-clipboard` route will need adding
> * The `QualifyingTestNewFromClipboard` component will need tweaking to consider the value of the `isTieBreaker` prop that is passed in through the router
> 
> If this PR is merged before the tie-breaker PR then the code can be added to the tie-breaker PR instead of course.
> 
> PS: Happy to make the above change myself when the time comes ;)

PLease create another ticket to deal with the issue reported here.

2021-05-09 23:04 UTC, lloback commented
@KateMJAC, if this was successfully testes, can you approve this PR, please?

2021-05-21 08:52 UTC, KateMJAC approved these changes
Positive results reported by UTG.

2021-05-21 20:33 UTC, merged