Display extra pupilage details
jac-uk/admin pull request #1291
Opened 2021-04-23 12:56 UTC by tomlovesgithub

## What's included?
More logic in the application view, presenting the more involved answers for barrister qualifications.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Ensure changes made on apply side [see apply #747 for more details] show in application view.

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
![image](https://user-images.githubusercontent.com/44227249/115870574-561f9900-a437-11eb-88b3-b1aa31fafcee.png)
![image](https://user-images.githubusercontent.com/44227249/115871171-19a06d00-a438-11eb-8612-da40fdd4bc9b.png)
![image](https://user-images.githubusercontent.com/44227249/115871212-2a50e300-a438-11eb-9b6d-90b4e4322393.png)

2021-04-26 08:37 UTC, HalcyonJAC approved these changes
Looks good to me :)

2021-04-26 08:40 UTC, warrensearle reviewed
See question in comments

2021-04-26 08:40 UTC, warrensearle commented on src/views/Exercises/Applications/Application.vue
> +                      v-if="item.notCalledToBar && item.notCalledToBar === true"
What is the benefit of having both these checks within the template?
 - `item.notCalledToBar` is truthy
 - `item.notCalledToBar` is true

Wouldn't `v-if="item.notCalledToBar"` do the same... or am I missing something?

2021-04-26 12:51 UTC, tomlovesgithub commented on src/views/Exercises/Applications/Application.vue
> +                      v-if="item.notCalledToBar && item.notCalledToBar === true"
right you are!

2021-04-28 15:11 UTC, mbrookeswebdev approved these changes

2021-05-04 09:43 UTC, warrensearle approved these changes
Looks good to me 👍

2021-05-04 12:04 UTC, KateMJAC requested changes
Hello Tom, please find the information below regarding the qualification requirements to become a barrister:
So key date for us is the date they complete pupillage – that is when they qualify. But if they have not been required to undertake pupillage, it is the date they are called to the Bar. Section 51(6) of the TCE Act 2007 states: 

For the purposes of section 50 and this section, a person shall be taken first to become a barrister—
(a)when the person completes pupillage in connection with becoming a barrister, or
(b)in the case of a person not required to undertake pupillage in connection with becoming a barrister, when the person is called to the Bar of England and Wales.

Can you please confirm the informaton that informed the decision to include the 'I have not been called to the bar' check box?

2021-05-13 15:55 UTC, tomlovesgithub commented
Hi Kate,
re: the pupilage stuff, i understand that the required info is:
Date completed pupilage
OR
Date called to bar
The question here really is surrounding the kinds of validation and minimum satisfactory answer for the qualifications section of the application.
In building this out as i have done, currently the page cannot be saved or progressed until a date has been supplied for one or the other of the above mentioned dates.
However to facilitate any ‘unhappy’ or ‘edge case’ scenarios where for any reason a candidate cannot provide these dates, I’ve allowed this to be bypassed with the checkboxes, with the hopes candidates will be able to provide justification/further information in their details box.
I understand that 99% of candidates who dont have these dates would be disqualified as ineligible, however it seemed counterintuitive to build a dead end into the application, which could force the candidate to provide [inaccurate] information in order to be able to progress. 

- copied from slack

2021-06-02 14:45 UTC, KateMJAC commented
@tomlovesgithub all works fine on apply, however there are some fields/rows on admin that appear in certain scenarios when they shouldn't/don't need to. 

- If a candidate selects 'yes' to them completing pupillage and provided their dates, admin does not need to display the following: 'Called to the bar     No'.

The act of confirming 'yes' to completing pupillage and providing a date indicates that they weren't called to the bar, 

- If a candodate selects 'yes' on 'have you been called to the bar?' and provides a date, we do not need the following row: 'Did not complete pupillage notes'.

The didn't complete pupillage text field isn't on Apply if a candidate confirms they were called to the bar and provides a date, as no further information is required.

If you can remove these fields/rows from admin, I can then send it out to the UTG.

Thank you

2021-06-02 14:46 UTC, KateMJAC submitted a review, later dismissed
@tomlovesgithub all works fine on apply, however there are some fields/rows on admin that appear in certain scenarios when they shouldn't/don't need to. 

- If a candidate selects 'yes' to them completing pupillage and provided their dates, admin does not need to display the following: 'Called to the bar     No'.

The act of confirming 'yes' to completing pupillage and providing a date indicates that they weren't called to the bar, 

- If a candodate selects 'yes' on 'have you been called to the bar?' and provides a date, we do not need the following row: 'Did not complete pupillage notes'.

The didn't complete pupillage text field isn't on Apply if a candidate confirms they were called to the bar and provides a date, as no further information is required.

If you can remove these fields/rows from admin, I can then send it out to the UTG.

Thank you

2021-06-04 14:55 UTC, KateMJAC reviewed
@tomlovesgithub the above issues still appear on Admin.

2021-06-07 09:55 UTC, joy-ade commented
@tomlovesgithub Positive test from UTG, however we receive the following feedback in relation to upload section.

[UserTest4.docx](https://github.com/jac-uk/admin/files/6607853/UserTest4.docx)

2021-06-30 11:01 UTC, KateMJAC commented
Awaiting response from @tomlovesgithub before this ticket can be progressed.

2021-06-30 12:46 UTC, KateMJAC commented
This has been sent to UTG on 30/06/21 after final changes made by Tom. Will await feedback before final approval. 

Also before this ticket is released consideration needs to be given to how it may/may not impact open exercises.

2021-06-30 12:47 UTC, KateMJAC reviewed
This has been sent to UTG on 30/06/21 after final changes made by Tom. Will await feedback before final approval. 

Also before this ticket is released consideration needs to be given to how it may/may not impact open exercises.

2021-07-07 11:37 UTC, KateMJAC approved these changes
Positive result at UTG.

2021-07-08 12:45 UTC, merged