add character issues export button
jac-uk/admin pull request #1328
Opened 2021-05-14 09:47 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?

Adds a button to export the character information from a firebase cloud function that gathers the data. This request depends on a pull request for the digital-platform repository - [digital-platform#545](https://github.com/jac-uk/digital-platform/pull/545) which contains the report information.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Click the button.

Ensure the report that should be downloaded looks as specified.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

2021-05-17 16:43 UTC, tomlovesgithub approved these changes

2021-05-17 18:52 UTC, lloback requested changes
I am not sure if this ticket is only to show the button, but there was a 500 error from

https://europe-west2-digital-platform-develop.cloudfunctions.net/generateCharacterCheckReport

{"data":{"exerciseId":"JYQV9f6Vfz72yyGLaoX1"}}

=====

Please post a link to an exercise that this work (I understand that sometimes we have in the database very old exercises with corrupt data.

2021-05-17 18:52 UTC, lloback commented on src/views/Exercises/Show/Reports/CharacterIssues.vue
> +      const title = `Character Check Report - ${this.exercise.ref}`;
for backward compatibility, there should be a check for null / empty values. I tried to download Character Issues, from an exercise with no issues, and this value came as `undefined`:

`Character Check Report - undef`

A solution should be a check if there are issues before show the EXPORT ALL button.

2021-05-18 08:44 UTC, HalcyonJAC commented on src/views/Exercises/Show/Reports/CharacterIssues.vue
> +      const title = `Character Check Report - ${this.exercise.ref}`;
I've addressed this now - it should have been `referenceNumber` not ref, and I also check for it before downloading. It now also checks if there actually is any data i.e any applications.

The spec we have seems to download a report for all applications, even if none of them have character issues. I guess thats so it can be merged with something.

2021-05-19 20:26 UTC, warrensearle approved these changes
Looks good to me 👍 
Tested via the preview url and on exercise 53 I can:
✅ view character issues report on screen
✅ page, sort and basic search
✅ download data for all applications

2021-05-19 22:59 UTC, lloback approved these changes
This is ready to go.

2021-05-20 10:46 UTC, merged