Enable GitHub Code Analysis
jac-uk/admin pull request #1339
Opened 2021-05-21 10:59 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---
## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-05-21 20:26 UTC, lloback commented
Please insert information for testing. Also there is no ticket on Zenhub for this change.

2021-06-10 09:18 UTC, HalcyonJAC commented
> Please insert information for testing. Also there is no ticket on Zenhub for this change.

Done

2021-06-11 20:45 UTC, lloback requested changes

2021-06-11 20:45 UTC, lloback commented on .github/workflows/codeql-analysis.yml
> +    branches: [ develop ]
I think this is a great idea. 
We don't have the `develop` branch on almost all repositories. Isn't it now `main`?

2021-06-14 10:08 UTC, HalcyonJAC commented on .github/workflows/codeql-analysis.yml
> +    branches: [ develop ]
This has been changed from `develop` to `main`

2021-06-16 17:56 UTC, lloback approved these changes
✔︎✔︎✔︎

2021-06-18 13:43 UTC, tomlovesgithub approved these changes
Cool!

2021-06-23 08:50 UTC, KateMJAC approved these changes
Approved on the basis that both developer teirs approved.

2021-06-23 08:51 UTC, merged