Validate independent assessor details
jac-uk/admin pull request #1340
Opened 2021-05-21 15:17 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---
## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Edit an independant assessor for an application, the form fields should now be validated.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-05-24 09:23 UTC, mbrookeswebdev approved these changes
👍

2021-05-25 07:58 UTC, warrensearle requested changes
See comment otherwise all good 👍

2021-05-25 07:58 UTC, warrensearle commented on src/components/ModalViews/IndependentAssessorChange.vue
> +      if (this.isValid()) {
The `Form` component that's being extended here means that this can be simplified to:
```
async save(isValid) {
  if (isValid) {
```

2021-05-25 10:05 UTC, HalcyonJAC commented on src/components/ModalViews/IndependentAssessorChange.vue
> +      if (this.isValid()) {
@warrensearle  ok good shout. I have made that change now.

2021-05-25 10:10 UTC, warrensearle approved these changes

2021-06-02 10:31 UTC, KateMJAC reviewed
Sent to UTG, will update with response.

2021-06-02 15:13 UTC, KateMJAC commented
How to test directions sent to the UTG. I have received advice from Halcyon that further testing is required and I am awaiting further in formation on what testers need to do.

2021-06-02 15:16 UTC, KateMJAC reviewed
@HalcyonJAC, testers are reporting that they are getting error messages for invalid email addresses, however once corrected it is not allowing any edits to be saved.

2021-06-03 09:06 UTC, JeremykJAC commented
- [ ]  After editing an email address on admin it wouldn't let me save anything I edited, even if it wasn't the email field ( Kate has found a bug that needs fixing)

2021-06-03 10:32 UTC, HalcyonJAC commented
> 
> 
> @HalcyonJAC, testers are reporting that they are getting error messages for invalid email addresses, however once corrected it is not allowing any edits to be saved.

Hi @KateMJAC and @JeremykJAC - this bug has been fixed.

2021-06-07 09:15 UTC, KateMJAC commented
Ticket to be re-tested this week by UTG, after bug fix.

2021-06-08 12:31 UTC, joy-ade commented
@HalcyonJAC testers are still reporting problems with the format of email saved. see below

I've tested the email function and was able to save it with the errors as well as have it approved for submission.

<img width="513" alt="Capture PNG51" src="https://user-images.githubusercontent.com/72265322/121185174-b5a5fc80-c85d-11eb-820c-517b17badea6.PNG">

2021-06-08 14:22 UTC, HalcyonJAC commented
Hi @joy-ade.

Looking at your screenshot, the test was done on https://admin-develop.judicialappointments.digital/ which won't have the front-end email validation checks in place yet because the Pull Request for this ticket has not been merged yet. To test that the front-end validation works correclly please use the preview URL:  https://jac-admin-develop--pr1340-feature-validate-ind-cm1s7gkw.web.app

2021-06-08 15:29 UTC, joy-ade commented
@JeremykJAC Thanks l have tested and its works as it should.

2021-06-08 15:31 UTC, joy-ade approved these changes
Approved by product team and UTG

2021-06-22 13:15 UTC, merged