1351 character issues
jac-uk/admin pull request #1352
Opened 2021-05-25 14:28 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---
## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-05-27 08:46 UTC, joy-ade commented
@HalcyonJAC  I am sending this out to UTG

2021-05-27 15:05 UTC, mbrookeswebdev commented
I can see some code related to assessors ticket in this PR, should it be here(?)

With regards to the Character Issues:

It probably applies to quite a few places in our app but where there is no data, the page displays nothing. Maybe we should display a message to that effect.

I've applied to an exercise JAC00298, which uses character info v2 [as this candidate](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/KOpW1w2nCyVe83rVFlz6/applications/applied/application/x7zPCnHFbcF9rqdueU0q). 

- When I've checked out [Character Issues page](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/KOpW1w2nCyVe83rVFlz6/reports/character) it displays blank where the issues should be listed, but the number of issues in the downloaded spreadsheet is correct.

I've applied to the old exercise JAC0053 as [the same candidate](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/wdpALbyICL7ZxxN5AQt8/application/RCUWUL01BKbCT3DCbF0z#full)

- On Character Issues page when I've selected All applications in the drop-down and click Next on the bottom of the page it takes me to the top of the same page instead of the next page.

- Character Issues displays blank where the issues should be listed. The downloaded report contains mixed info from both applications.

I've also tested on another candidate with less data ([old exercise](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/wdpALbyICL7ZxxN5AQt8/applications/applied/application/KtPwJAreAOaBZWP1Pcp9) and [new exercise](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/KOpW1w2nCyVe83rVFlz6/applications/applied/application/7VAfk16N52pKnaJ4mtby)), it seems downloaded data is mixed from both applications.

A couple of screenshots:
![screenshot1](https://user-images.githubusercontent.com/40855898/119849743-cae96580-bf04-11eb-9cbe-6c469629f950.png)
![Screenshot2](https://user-images.githubusercontent.com/40855898/119849758-cde45600-bf04-11eb-907f-89bca38315cf.png)

2021-05-27 17:06 UTC, warrensearle requested changes
✅ The on screen report appears to be working well
✅ The export data download is working
✅ The code looks fine though see issue below

The following needs to be addressed:

1. This PR includes changes from the IAs validation work, so it's not possible to approve this without approving both changes. Are you able to disentangle the two pieces of work? If not then we should not merge this until IAs validation has been approved (and merged).

2. The downloaded file doesn't include the issues and events displayed on screen. In fact it looked like the wrong download.

3. The Stages and Status dropdowns work well but I wonder if the layout could be tidied. On desktop right now they appear one above the other which pushes the report content quite far down the screen. 
<img width="964" alt="image" src="https://user-images.githubusercontent.com/8524401/119867464-d42efe00-bf15-11eb-8d44-44235540babc.png">
Having the dropdowns side-by-side might help.

2021-05-28 09:01 UTC, mbrookeswebdev commented
@HalcyonJAC I've done a quick check. The issues appear on the page, which is great.

When I click 'Next' [on this page](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/wdpALbyICL7ZxxN5AQt8/reports/character#) it still takes me to the top of the same page, not to the next page with candidates.

Also, the downloaded data still seems to be incorrect. For example [this candidate](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/KOpW1w2nCyVe83rVFlz6/application/7VAfk16N52pKnaJ4mtby#full) has 3 issues listed in the app, 5 issues on the Char Issues page and 6 in the download file.

2021-05-28 09:36 UTC, HalcyonJAC commented
> 3\. The Stages and Status dropdowns work well but I wonder if the layout could be tidied. On desktop right now they appear one above the other which pushes the report content quite far down the screen.

I have made a styling change so that the dropdowns are now side-by-side. Note: I tried doing this using the gov-uk classes but couldn't get it to work correctly that way, so used a small amount of CSS instead.

2021-05-28 10:47 UTC, HalcyonJAC commented
> Also, the downloaded data still seems to be incorrect. For example [this candidate](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/KOpW1w2nCyVe83rVFlz6/application/7VAfk16N52pKnaJ4mtby#full) has 3 issues listed in the app, 5 issues on the Char Issues page and 6 in the download file.

I checked this out and the `applications` document has both `characterInformation` and `characterInformationV2` stored against it (see below), which is what is causing the inconsistancy. In production this (bad data) shouldn't happen.

![image](https://user-images.githubusercontent.com/79906532/119972674-67197800-bfaa-11eb-959b-4d17988cd3d1.png)

2021-05-28 11:02 UTC, warrensearle commented
>I checked this out and the applications document has both characterInformation and characterInformationV2 stored against it (see below), which is what is causing the inconsistancy. In production this (bad data) shouldn't happen.
@HalcyonJAC I like your optimism however thinking perhaps we could code against this anyway. If `characterInformationV2` exists then ignore `characterInformation`. Being more pessimistic I think we _could_ have applications with both fields ☹️

2021-05-28 11:02 UTC, HalcyonJAC commented
> When I click 'Next' [on this page](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/wdpALbyICL7ZxxN5AQt8/reports/character#) it still takes me to the top of the same page, not to the next page with candidates.

I don't know how to fix this!

2021-05-28 11:26 UTC, mbrookeswebdev commented
> I checked this out and the `applications` document has both `characterInformation` and `characterInformationV2` stored against it (see below), which is what is causing the inconsistancy. In production this (bad data) shouldn't happen.

If I understand correctly, the data in the report should contain info from [the Character Information section of the application](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/wdpALbyICL7ZxxN5AQt8/application/KtPwJAreAOaBZWP1Pcp9#full). Couldn't we do it like this - if `(this.exercise._applicationVersion && this.exercise._applicationVersion === 2) then use characterInformationV2, if not then use characterInformation`. [This is how the correct info displayed in Full details tab.](https://github.com/jac-uk/admin/blob/main/src/views/Exercises/Applications/Application.vue)(line 317 onwards).

> When I click 'Next' on this page it still takes me to the top of the same page, not to the next page with candidates.
I don't know how to fix this!

With regards to the table, it is a quite complex component... [Maybe my WIP branch would help](https://github.com/jac-uk/admin/compare/feature/1327-enable-request-of-character-check-form-completion#diff-6f061963ddb50672ea6134049e69c0e2111a0071e2c90f16045bfc85a3e27ab3), check out how I've used the table in `src/views/Exercises/Tasks/CharacterChecks.vue` for my consent form prototype.

2021-05-28 14:06 UTC, HalcyonJAC commented
> I can see some code related to assessors ticket in this PR, should it be here(?)

I must have pushed the assessor changes onto this branch by mistake. I have removed these changes from this branch now.

2021-05-28 14:11 UTC, HalcyonJAC commented
> If I understand correctly, the data in the report should contain info from [the Character Information section of the application](https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app/exercises/wdpALbyICL7ZxxN5AQt8/application/KtPwJAreAOaBZWP1Pcp9#full). Couldn't we do it like this - if `(this.exercise._applicationVersion && this.exercise._applicationVersion === 2) then use characterInformationV2, if not then use characterInformation`. [This is how the correct info displayed in Full details tab.](https://github.com/jac-uk/admin/blob/main/src/views/Exercises/Applications/Application.vue)(line 317 onwards).

The way I have done it is by altering the `flagApplicationIssues` function in the Digital Platform (after a conversation with Warren) so that the issue details end up being part of the `applicationRecords.characterIssues` array, whether the source was character info v1 or v2. The reason it isn't working right for the application you picked is that is happens to have character info v1 and v2 on it, which wouldn't usually happen.

2021-05-28 17:05 UTC, warrensearle approved these changes

2021-06-01 14:32 UTC, tomlovesgithub commented on src/views/Exercises/Show/Reports/CharacterIssues.vue
> +    <div class="govuk-grid-column-full">
This should sort the styling and remove the need for custom CSS
```
...
    <div class="govuk-grid-column-full">
      <div class="govuk-button-group">
        <Select
          id="exercise-stage"
          v-model="exerciseStage"
          class="govuk-!-margin-right-2"
        >
          <option 
...
```

2021-06-01 14:35 UTC, tomlovesgithub approved these changes
Look good to me, y only suggestions would be the CSS changes mentioned above and perhaps renaming the download, which could perhaps be expanded into another ticket so the filename carries filtering information.

2021-06-08 14:38 UTC, HalcyonJAC commented
Hi 

The preview URL for this is https://jac-admin-develop--pr1352-feature-1351-charact-xkdr9f3a.web.app

...and it does not expire until Sun, 27 Jun 2021

2021-06-10 15:52 UTC, joy-ade commented
This needs changes post qualification experience is missing from the download

2021-06-10 16:34 UTC, HalcyonJAC commented on src/views/Exercises/Show/Reports/CharacterIssues.vue
> +    <div class="govuk-grid-column-full">
Thanks for @tomlovesgithub, worked like a charm :)

2021-06-11 09:03 UTC, HalcyonJAC commented
> This needs changes post qualification experience is missing from the download

I have fixed this now.

2021-06-15 13:24 UTC, joy-ade approved these changes
Approved by product team and UTG

2021-06-22 13:13 UTC, merged