#1077 Display responses provided in a previous test
jac-uk/admin pull request #1379
Opened 2021-06-25 22:37 UTC by lloback

This is a new PR following up from an old PR for which the test URL expired.

https://github.com/jac-uk/admin/pull/1259

2021-06-30 21:23 UTC, warrensearle approved these changes
Still looks good to me.
✅ Code reviewed
✅ Tested via preview URL: can see responses for a qt moved to mop up day

2021-06-30 21:37 UTC, warrensearle commented
@KateMJAC this was previously approved by developers just, potentially, needs UTG approval.

2021-07-01 10:51 UTC, HalcyonJAC approved these changes

2021-07-01 14:22 UTC, KateMJAC commented
Sent to the UTG for testing today - 1/07/21. Awaiting feedback.

2021-07-02 08:47 UTC, tomlovesgithub requested changes

2021-07-02 08:47 UTC, tomlovesgithub commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> +      return this.response ? true : false;
This might mess with the QT reset functionality, due to be updated and rolled out soon.
Is there any way that this function can facilitate what it needs to for this PR, but maintain a check on the status and statuslog?

2021-07-05 10:33 UTC, mbrookeswebdev approved these changes

2021-07-09 09:21 UTC, tomlovesgithub approved these changes

2021-07-16 13:26 UTC, joy-ade commented
@lloback @warrensearle can you resolve the conflict in this ticket pls.

2021-07-16 13:28 UTC, joy-ade approved these changes
Receive positive feedback from UTG

2021-07-20 13:49 UTC, warrensearle commented
Fixed merge conflicts and moving to 'Done (ready to merge)'

2021-07-20 15:43 UTC, merged