260/admin application edits
jac-uk/admin pull request #1459
Opened 2021-07-29 14:30 UTC by tomlovesgithub

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---
## What's included?
This PR asserts a new pattern for the `application.vue`  grouping it into sections which contain `editableField.vue`s 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
### Feature only available to auth users
- Go to an exercise.
- View an application
- Click 'Edit Application'
- Observe changes on the page;
  - 'Change' links appear
  - Button changes to 'Done editing' 
  - 'Add' and 'Remove' buttons for list sections.

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.
![image](https://user-images.githubusercontent.com/44227249/127509644-d07b8e3d-3e77-4837-a7f5-af0bfa5e18fc.png)
![image](https://user-images.githubusercontent.com/44227249/127509723-eb534cee-9b7c-4e9e-b3d1-efa08df1ac55.png)
![image](https://user-images.githubusercontent.com/44227249/127509867-cf9a139f-dc0d-405d-8195-cd8548508af9.png)

![image](https://user-images.githubusercontent.com/44227249/127510055-71ea3270-f9b0-44bf-9ca3-28fe90194c1d.png)

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-07-29 17:35 UTC, warrensearle submitted a review, later dismissed
@tomlovesgithub this PR appears to include lots of file changes
<img width="179" alt="image" src="https://user-images.githubusercontent.com/8524401/127538310-37c90c14-62fd-4378-9b90-10fce602f765.png">

did something go wrong with a merge/rebase? we need to sort it out before merging this PR

2021-08-03 13:38 UTC, mbrookeswebdev commented
@tomlovesgithub It looks like there are some failing tests + should /QualifyingTest/Response/View.vue and QualifyingTests/QualifyingTest/View.vue be removed from your PR?

2021-08-17 11:05 UTC, mbrookeswebdev commented
It seems there is quite a lot of unused space in that table. Wouldn't be easier to place the fields underneath, for example if editMode = true, then plug in the components from Apply to input and save data, if editMode = false, show Summary components existing in Admin or take something from Apply and adopt? Just my 2 pence... :) 

![Edits3](https://user-images.githubusercontent.com/40855898/129715482-6a8626a8-690a-4654-940f-58f2ecda2cd8.png)
![Edits](https://user-images.githubusercontent.com/40855898/129715487-ab8d26d5-0b57-4819-a911-36ac49c96348.png)

2021-09-28 14:41 UTC, HalcyonJAC requested changes
I've highlighted some things - in this MR there's quite a bit of commented code...

Also I can't get this to run so can't function test it, I'm getting this, but I don't think its this MR doing it, and the error is nonsensical.

![image](https://user-images.githubusercontent.com/79906532/135109555-059b5351-c48f-4344-912e-efc8cb9d9d76.png)

2021-09-29 16:22 UTC, tomlovesgithub commented on src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/View.vue
> +      <!-- <button
It never could! 
Button was annoying me as it is non-functional and should be removed.
Don't think this change should necessarily be within this PR tho so ill shall return it to before

2021-09-29 16:22 UTC, tomlovesgithub commented on src/store/candidates.js
> +    // saveCharacterInfo: async (context, { data, id }) => {
No! Good catch, this was a early mistake i picked up on just before i opened the PR, commented it out to double check it wasn't needed, removed now!

2021-09-30 08:32 UTC, HalcyonJAC approved these changes
Great - thanks for making those changes 👍 :)

2021-11-10 11:20 UTC, warrensearle commented
Hi @tomlovesgithub 

Upon using the preview URL I observed the following issues:

No editor form for prefessional background:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/8524401/141101466-23bcd7be-9acd-494c-8670-bb2255e687dc.png">

Location preferences editor form works for Single Choice but not for Multi or Ranked Choices
<img width="633" alt="image" src="https://user-images.githubusercontent.com/8524401/141102210-fd0bc4d4-0971-4315-a43d-f3e44baccf00.png">

Experience titles are field names rather than proper language
<img width="408" alt="image" src="https://user-images.githubusercontent.com/8524401/141102548-e4e77f8f-35f5-45df-a308-abd41ad7fdef.png">

Additional selection criteria 'words' layout needs improvement (see that the content appears lower than the 'words' label and the 'change' link)
<img width="881" alt="image" src="https://user-images.githubusercontent.com/8524401/141103000-27964c3c-eb43-4999-8878-e18607a1882f.png">

Qualifications & Memberships are not editable or are being displayed when they shouldn't be
<img width="947" alt="image" src="https://user-images.githubusercontent.com/8524401/141104030-ed7a29cf-c321-4c50-b227-3400590d9604.png">

2021-11-10 11:40 UTC, warrensearle submitted a review, later dismissed

2021-11-10 11:40 UTC, warrensearle commented on src/views/Candidates/CandidatesView.vue
> +import CharacterInformationV1Summary from '@/views/Exercise/Applications/CharacterInformationV1Summary.vue';
@tomlovesgithub why did you change the name of this file?
imo `CharacterInformationSummaryV1` is better than `CharacterInformationV1Summary`.
With `CharacterInformationV1Summary` we risk losing the version information `V1`

2021-11-10 11:40 UTC, warrensearle commented on src/views/Exercise/Details/Overview.vue
> +              <!-- <span class="govuk-heading-l govuk-!-margin-top-1">{{ exercise.applications.draft || 0 }}</span> -->
??

2021-11-10 11:40 UTC, warrensearle commented on src/views/InformationReview/AssessmentsSummary.vue
> +      }
This is repeated in a few files please refactor.

https://github.com/jac-uk/admin/pull/1459#discussion_r729747511

2021-12-09 16:12 UTC, warrensearle approved these changes
Lots of changes here!
✅ Code reviewed
✅ Tested (lightly) via Preview URL

2021-12-10 10:17 UTC, warrensearle commented
@tomlovesgithub can you fix conflicts and then merge this

2021-12-14 16:28 UTC, joy-ade approved these changes
Positive test by product Team

2021-12-15 15:22 UTC, HalcyonJAC approved these changes
The date field allows invalid dates to be entered. Mainly the year part of the input would perhaps benefit from further validation.  I would suggest not allowing a year that is before 1900, or allow the programmer to specify a min-date allowed. Note: From memory, I think added a min-date validation option to the <Field> widget  at some point.

![image](https://user-images.githubusercontent.com/79906532/146213618-6c377e84-2444-470d-9136-d10bd4a4a1c7.png)

2021-12-17 10:45 UTC, joy-ade commented
@tomlovesgithub Can you make personal details section editable for the Administrators please.

2021-12-21 10:29 UTC, warrensearle approved these changes

2021-12-21 10:54 UTC, merged