#1078 - Create custom report
jac-uk/admin pull request #1469
Opened 2021-08-12 09:38 UTC by HalcyonJAC

## What's included?
A new way to inspect data within the dashboard and generate / save your own reports.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to an Exercise
Click the reports tab
Click the Custom report link on the left nav

Functionality:
1. Select a column from the dropdown to show the values in a table
2. Add multiple columns, delete them by clicking and re-order by dragging.
3. Change the report type to count to view aggregated results
4. On the count report, click one of the values to add a 'where clause' which limits the results
5. Save a report by clicking Save Report at the top right of the page, give it a name. Then switch to a different exercise and try to load the report.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-08-18 16:40 UTC, tomlovesgithub requested changes
still getting console errors when testing locally ;?

2021-08-18 16:40 UTC, tomlovesgithub commented on src/views/Exercise/Reports/Custom.vue
> +  data() {
`isLoading` and `loadFailed` need to be added to the data here.

2021-08-20 14:28 UTC, warrensearle approved these changes
Awesome 👍

2021-09-10 12:29 UTC, mbrookeswebdev approved these changes

2021-09-23 07:58 UTC, HalcyonJAC commented on src/views/Exercise/Reports/Custom.vue
> +  data() {
Hi,

This data has been added to the component.

2021-09-30 12:05 UTC, joy-ade reviewed
feedbacks from UTG  "select a column to display" - can that be re-ordered to have application info 1st maybe as its likely the most people would filter on his on the application status

2021-09-30 15:08 UTC, joy-ade commented
@HalcyonJAC @JeremykJAC Can you include and export button on this report pls.

2021-09-30 15:09 UTC, joy-ade reviewed
Feedback form UTG Can we download this report pls.

2021-10-05 12:25 UTC, HalcyonJAC commented
@joy-ade Hi - I've made some of the changes but I think there might be some more work to do on this later depending.

- Order of options is changed
- Added jurisdiction and location
- fixed a bug with saving reports
- added some validation on saving reports
- adding a message to show the report was saved

2021-11-08 10:49 UTC, joy-ade approved these changes
Approved by Product team and UTG

2021-11-08 10:51 UTC, tomlovesgithub approved these changes

2021-11-08 10:53 UTC, merged