#1497 scenario test panel packs
jac-uk/admin pull request #1509
Opened 2021-10-27 16:28 UTC by HalcyonJAC

This PR closes #1497

---
## What's included?

This pull request exports scenario tests to a google drive folder.

Please also see https://github.com/jac-uk/digital-platform/pull/655

A new tab has been added to the tasks screen - with `Sift` and `Selection Day` we now have another one called `Scenario Responses`. The functionality is identical to these other two, except for when you click export, the process exports the scenario tests the candidate has taken into a google drive folder rather than their application data. Any person who has done no test does not have a folder created for them, and 1 file is created within that folder for every test that user has completed.

Candidates available to be put onto a panel on this screen must have the status of ` Passed scenario test` which is referred to in a few places as `Passed first test`.

The exported document contains the the test title, the candidate name, and and export of every question including the question that was asked, the word count (and how many words the candidate entered), and the answer they gave in full.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

- Create an Exercise that *includes a Scenario Test Date*
- Apply to that Exercise
- Close applications, and create a scenario test.
- Complete the scenario test
- Go to Scenario Tests, and add that candidate to a panel, and export
- Verify the Panel Folder appears in Google Drive, containing the applicants folder, and their test export file.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

Despite this code changing slightly the export procedure used by `sift` and `selection`, it is separated in code.

## Additional context

![image](https://user-images.githubusercontent.com/79906532/139254911-b52cdaeb-ef21-4bd1-a880-b1fc2ff61b44.png)

[Demonstration Video](https://1drv.ms/v/s!AnaqEeaLnRUmioZdWQVhk8O5D6eCrw?e=rwwJTI)

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-11-04 11:06 UTC, mbrookeswebdev approved these changes

2021-11-08 11:34 UTC, joy-ade reviewed
Approved by product team out to UTG 8/11/2021

2021-11-10 10:17 UTC, warrensearle requested changes
Looks good, just a small change to the status used for candidates who took the scenario test.

Also tested via the preview URL and looks like the corresponding [digital platform](https://github.com/jac-uk/digital-platform/pull/655) changes need to be deployed (which will happen when that PR is merged). Right now the folder created on google drive contains application documents rather than QT documents.

2021-11-10 10:17 UTC, warrensearle commented on src/components/PanelPacks/PanelPacks.vue
> +            status: APPLICATION_STATUS.PASSED_SCENARIO_TEST,
This should be `APPLICATION_STATUS.PASSED_FIRST_TEST` to identify all candidates who passed the first CA & SJ test(s) and so were eligible to sit the scenario test.

2021-11-10 10:38 UTC, HalcyonJAC commented on src/components/PanelPacks/PanelPacks.vue
> +            status: APPLICATION_STATUS.PASSED_SCENARIO_TEST,
I've updated this - the reason I had it set to passed scenario was that there will be no data to export if they haven't sat it yet, but then I suppose they need to do the test and have it marked with the export before it is passed.

2021-11-10 11:45 UTC, warrensearle commented on src/components/PanelPacks/PanelPacks.vue
> +            status: APPLICATION_STATUS.PASSED_SCENARIO_TEST,
Yes we could consider only enabling the link in Tasks to be present after the scenario test date(s)

2021-11-10 11:53 UTC, warrensearle approved these changes
Looks good and is ready for testing 👍 
Perhaps we might want to refine the 'Scenario Responses' link to say something else and perhaps we might not want to display the link until the scenario test has happened. This can be decided upon by product team / design group.

2021-11-12 13:06 UTC, joy-ade approved these changes
Approved by UTG

2021-11-22 13:21 UTC, tomlovesgithub approved these changes

2021-11-22 13:28 UTC, merged