#664/welsh posts
jac-uk/admin pull request #1519
Opened 2021-11-26 17:04 UTC by tomlovesgithub

draft pr

2021-12-07 14:04 UTC, joy-ade reviewed
positive test by product team out to UTG 07/12/2021

2021-12-08 11:00 UTC, joy-ade approved these changes
Approved by UTG

2021-12-09 14:54 UTC, warrensearle requested changes
Minor change to code - see comments. 😄

2021-12-09 14:54 UTC, warrensearle commented on src/views/Exercise/Applications/Application.vue
> +                  v-if="exercise.welshRequirementType.some((req) => req === 'welsh-speaking')"
@tomlovesgithub it'd be worth moving this out of the template code and into a computed, or method, instead. In order to keep the template simple

2021-12-14 15:49 UTC, HalcyonJAC commented
Hi guys. This pull request has merge conflicts but I don't know much about the code in `develop` that it is conflicting with, so I am going to need help resolving this one...

PS: Fortunately the conflicts is only in 1 file.

2021-12-22 11:45 UTC, warrensearle approved these changes

2022-01-04 12:00 UTC, joy-ade approved these changes
Approved by product team

2022-01-04 12:01 UTC, merged