digital-platform#666 Change to PAJE answers
jac-uk/admin pull request #1554
Opened 2022-01-18 16:45 UTC by warrensearle

## What's included?
Update to support the change to PAJE answers, as outlined in https://github.com/jac-uk/digital-platform/issues/666

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
In Apply:
- Create an application for a **legal** exercise
- Complete the Equality and Diversity survey taking note of the answer provided to the question 'Have you taken part in the Pre-Application Judicial Education Programme (PAJE)?'

In Admin:
- Go to Draft Applications (for the relevant exercise) and click on the application you just created
- In application view locate 'Equality and diversity information' and the answer displayed for 'Participated in Pre-Application Judicial Education Programme'
- Observe that the answer displayed matches the answer provided by the candidate
- In Apply try changing the selected answer and in Admin observe that the correct answer is displayed

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-01-19 14:13 UTC, tomlovesgithub requested changes
![image](https://user-images.githubusercontent.com/44227249/150147390-5b22a3ff-0d05-40fe-b73b-cfe180b15b23.png)
These new options need to be available for admins when editing answers too!

2022-01-19 15:02 UTC, HalcyonJAC approved these changes
Looks good to me

2022-01-19 17:10 UTC, tomlovesgithub approved these changes

2022-02-07 15:48 UTC, andrew-isaac approved these changes
Checked wording and looks good to me

2022-02-07 15:51 UTC, andrew-isaac approved these changes

2022-02-11 09:19 UTC, merged