#1525 Static Report
jac-uk/admin pull request #1558
Opened 2022-01-26 09:46 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---
## What's included?
Add qualified date and post-qualification experience date columns to custom report

## Who should test?
✅ Product owner
✅ Developers

## How to test?
Enter an Exercise, go to Reports and then Custom Report. Click the dropdown for Select a column to display and click on Add `Qualifications` and `Post-qualification experience`. The two columns will then load on screen, just below the dropdown box. 

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-01-26 09:58 UTC, warrensearle approved these changes
👍

2022-02-10 20:10 UTC, andrew-isaac requested changes
I tested  this on exercise using 3 candidates data. How does the report cope when trying to populate this for over 1000 candidates? I was trying to use a similar feature on Recorder  in the production environment this week and this still hadn't populated my data after waiting 5 minutes. Some exercises can have up to 3,000 applications where we need to pull data and reports for our stakeholders. 

Is there a way we an load a larger number of data into the report and test how long it would take to populate?  I can then feed this back to team in terms of expectations depending on the size of their exercise and the number of applications they receive.  Otherwise they will just keep pressing buttons and getting annoyed :)

2022-02-11 08:59 UTC, HalcyonJAC commented
Hi @andrew-isaac 

There could be some performance improvements on the report. It is pulling in a lot of data and does take a while to load. Please can you raise a new issue for your comment. This issue is addressing - Add qualified date and post-qualification experience date columns to custom report.

Thanks
Jeremy

2022-02-15 16:57 UTC, tomlovesgithub approved these changes

2022-02-15 16:57 UTC, andrew-isaac approved these changes

2022-02-15 16:59 UTC, merged