#1620 - character issues google doc report
jac-uk/admin pull request #1624
Opened 2022-05-23 08:28 UTC by HalcyonJAC

**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---
## What's included?
Character Issues - A new Export to Google Docs button.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- View an exercise with character issues
- Click the Export to Google Docs button
- A document should be downloaded, containing an export of the character issues

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Example layout:
https://docs.google.com/document/d/12cTMJEC9j3LbR34j_4cb4iT-oHX-VthQ/edit#

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-06-01 11:37 UTC, warrensearle requested changes
Please post a link to the Preview URL when you have one.

Please also change the base branch so we can see just the relevant changes made here.

2022-06-06 19:17 UTC, andrew-isaac approved these changes

2022-07-08 09:37 UTC, warrensearle approved these changes

2022-07-08 09:39 UTC, merged

2022-07-26 12:58 UTC, andrew-isaac commented
@JeremykJAC  - Can we close this as I presume this is what we pushed to live last week?