#1677 Character Report Part 2 - Show all character issues from other exercises
jac-uk/admin pull request #1678
Opened 2022-07-14 09:39 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪
- [ ] Delete this checklist when you've completed it

---
## What's included?
On Character Issues page show all character issues from other exercises.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-07-27 12:35 UTC, andrew-isaac reviewed
Fantastic work ! This can be moved to UT lane :)

2022-08-02 10:05 UTC, warrensearle requested changes
Looks like there are some lint fixes needed plus please see comment regarding using constants and camelCase for our database values

2022-08-02 10:31 UTC, tomlovesgithub commented
Functions great, but agree with warrens points re: constants and db convention! Will re review after those have been addressed.

2022-08-02 11:08 UTC, HalcyonJAC commented on src/views/Exercise/Reports/CharacterIssues.vue
> +                    Mixed
Thank you for your feedback.

2022-08-03 15:58 UTC, warrensearle approved these changes
Hey @HalcyonJAC this is much better, thank you 👍 

Approved, though we will need to keep an eye on this one. The `getOtherApplicationRecords` method loops through all the applications and for each one queries firebase to obtain all the candidate's other applications. Should be ok but there's now quite a lot of document reads going on in the front end.

For other reports we went with the pattern of generating a single `report` document containing all the data needed. I can see how this approach may not be quite right for the functionality here (storing outcomes and notes) however is something to keep in mind as this functionality evolves.

2022-08-03 16:22 UTC, tomlovesgithub approved these changes

2022-10-05 08:56 UTC, andrew-isaac approved these changes

2022-10-05 09:01 UTC, merged