#1690 Update independent assessments UI
jac-uk/admin pull request #1696
Opened 2022-07-27 08:04 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪
- [ ] Delete this checklist when you've completed it

---
## What's included?
It is inconsistent with other screens. Change it to this one - https://www.figma.com/file/toOjVICtIYu5WmNbhJuyxm/JAC?node-id=146%3A1970

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-08-30 17:31 UTC, warrensearle requested changes
Looking good, just a question about simplifying the code to make it more maintainable which we can discuss if you like.

2022-08-30 17:31 UTC, warrensearle commented on src/views/Exercise/Tasks/IndependentAssessments.vue
> +              placeholder: 'Search candidate names',
There are lots of instances of the `Table` component whilst only one shows at a time. As the contents are so similar can we consider using just one instance? Right now if we wish to change something, for example the custom-search plugin, then we will need to change it in 5 places.

2022-09-02 08:48 UTC, warrensearle approved these changes
LGTM 👍

2022-09-06 11:17 UTC, tomlovesgithub approved these changes

2022-09-07 16:01 UTC, andrew-isaac requested changes
I sent out Adam Schinner IAs on this exercise - https://jac-admin-develop--pr1696-feature-1690-update-seca6n3n.web.app/exercise/RykU5zMVsXd3cwa5yqqQ/tasks/independent-assessments#requested  He moved to requested and I then cancelled it to move him back to not requested. I sent out the IA again but he has now disappeared from all lists and I can't locate him. I did this again with another candidate and it seemed to be ok?

Also when moving between tabs I am having to refresh to get the data to update - It did warm up after time so may be it is just where the data was populating?

2022-10-13 09:07 UTC, warrensearle commented
UT results: https://drie.slack.com/archives/C01R6GAAETG/p1665587137605259?thread_ts=1665580898.414769&cid=C01R6GAAETG

2022-10-13 09:54 UTC, merged