#1694 Add commas to numbers
jac-uk/admin pull request #1698
Opened 2022-07-27 12:31 UTC by HalcyonJAC

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪
- [ ] Delete this checklist when you've completed it

---
## What's included?
Add commas to numbers so they are easier to read. This will be anywhere we display numbers on the platform:
- [x] Applicant count on the Exercises table
- [x] Overview 
- [x] pageApplications menu
- [x] Stages menu
- [x] Reports

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to the admin platform and check number display

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-07-29 15:39 UTC, andrew-isaac approved these changes

2022-08-02 10:15 UTC, warrensearle requested changes
It's good to try and keep our template code as simple and robust as possible.

With that in mind could we update these changes to use a filter instead, along the lines of:

```{{ diversity.totalApplications | formatNumber }}```

instead of

```{{ diversity.totalApplications.toLocaleString('en-GB') }}```

Within the `formatNumber` filter we can then check the value exists before we do anything to it and moving forward we will have one place to make changes, should we need to change anything.

2022-08-02 11:22 UTC, tomlovesgithub approved these changes

2022-08-03 16:02 UTC, warrensearle approved these changes
@HalcyonJAC excellent this is much nicer... and units tests too 👍

2022-08-03 16:22 UTC, tomlovesgithub approved these changes

2022-08-26 08:55 UTC, merged