scripts formatting env:script
jac-uk/admin pull request #1720
Opened 2022-08-24 12:42 UTC by tomlovesgithub

## What's included?
Scripts in `package.json` now follow `[ENV]:[SCRIPT]` format and are ordered for easier readability.

## Who should test?
✅ Developers

## How to test?
Observe `package.json` and ensure scripts are correctly formatted and named, ordered and not repeated.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:OFF
_can be OFF, DEVELOP or STAGING_

2022-08-24 16:04 UTC, warrensearle requested changes
Great, thanks @tomlovesgithub. You will also need to update the github workflows to use the new script names.
e.g. see here: https://github.com/jac-uk/admin/blob/d2cdc1350b92ed58afbaf221b81b8434257c764c/.github/workflows/on-pull-request.yml#L109

`build-${{ env.environment }}` will need changing to `${{ env.environment }}:build`

Please check all the workflows 😄

2022-08-25 09:20 UTC, warrensearle approved these changes
👍

2022-08-26 08:05 UTC, HalcyonJAC approved these changes

2022-09-07 15:29 UTC, andrew-isaac approved these changes

2022-10-11 09:53 UTC, merged