#1718 Exercise Status
jac-uk/admin pull request #1747
Opened 2022-10-05 16:21 UTC by HalcyonJAC

## What's included?
Show exercise state next to the close date in the table. It should state the following
-  Live
-  Draft
-  Published on website
-  Unpublished on website
-  Archived

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to Exercises page and check the status.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP

2022-10-12 09:38 UTC, andrew-isaac requested changes
Can we change the `True` to say `Yes` please?

![image](https://user-images.githubusercontent.com/97609636/195308077-3bb39e8b-cc83-48ba-b3e7-93c476518fa5.png)

2022-11-03 09:38 UTC, andrew-isaac approved these changes

2022-11-03 09:48 UTC, warrensearle approved these changes
LGTM 👍

2022-11-03 17:29 UTC, tomlovesgithub approved these changes

2022-11-07 09:19 UTC, merged