#1714 ACRO Template on Agency Reports
jac-uk/admin pull request #1748
Opened 2022-10-06 15:35 UTC by HalcyonJAC

## What's included?
Export ACRO report. Here is the [ACRO form](https://app.zenhub.com/files/201485031/c5600bcc-2f59-4efc-ae51-5bd724429bba/download).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
1. Go to Agency Reports of an exercise and click "Export data".
2. Check if data is populated.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://user-images.githubusercontent.com/79906532/195061996-66231234-1cf2-43c4-8343-529c8175198e.mov

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP

2022-10-10 11:45 UTC, warrensearle requested changes
@HalcyonJAC when we reviewed and estimated this task we agreed to keep things simple and just get the columns in the existing download to match those in the acro template. That's it. Simples!

2022-10-11 10:33 UTC, warrensearle approved these changes
Great, thank you 👍

2022-10-13 10:17 UTC, tomlovesgithub approved these changes

2022-10-13 19:11 UTC, andrew-isaac approved these changes

2022-11-02 09:19 UTC, merged