#1764 Application Submission Reminder
jac-uk/admin pull request #1794
Opened 2022-11-09 16:31 UTC by HalcyonJAC

## What's included?
Send a reminder email to all applications in Draft.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP

2022-11-17 09:08 UTC, JeremykJAC commented
UT Feedback - Reports that this isn't going into the queue. Can we look into this?

2022-11-17 11:47 UTC, andrew-isaac requested changes
It worked for me but when pressing the `send reminder` button it took 2-3 tries for it to acknowledge I had pressed it and emails were being processed. I think we need to show the platform is `processing` and then `done` with a message stating to admin where they can find confirmation of the reminders going out.

In the second paragraph "This is a reminder that the closing date for receipt of completed applications is Thursday, November 9, 2023" we need to add the closing time of 13:00 as candidates could think it is COP on the date.

![image](https://user-images.githubusercontent.com/97609636/202437838-a1a5d6e8-3575-4d5e-87a4-eb7b175d375a.png)

2022-11-30 10:35 UTC, HalcyonJAC commented
> It worked for me but when pressing the `send reminder` button it took 2-3 tries for it to acknowledge I had pressed it and emails were being processed. I think we need to show the platform is `processing` and then `done` with a message stating to admin where they can find confirmation of the reminders going out.
> 
> In the second paragraph "This is a reminder that the closing date for receipt of completed applications is Thursday, November 9, 2023" we need to add the closing time of 13:00 as candidates could think it is COP on the date.
> 
> ![image](https://user-images.githubusercontent.com/97609636/202437838-a1a5d6e8-3575-4d5e-87a4-eb7b175d375a.png)

The closing time of 13:00 is added. Please check it again.

2022-12-01 21:21 UTC, warrensearle requested changes
See comments in this ticket and digital platform ticket with regards having a specific permission for this feature.

2022-12-01 21:21 UTC, warrensearle commented on src/views/Exercise/Applications/List.vue
> +                PERMISSIONS.notifications.permissions.canCreateNotifications.value,
See comment on related digital platform ticket.
I suggest we introduce a new permission to cover this functionality - e.g. `canSendApplicationReminders`

2022-12-02 13:24 UTC, warrensearle commented on src/views/Exercise/Applications/List.vue
> +                PERMISSIONS.notifications.permissions.canCreateNotifications.value,
Yes you're making sense however we shouldn't need any changes in firestore rules...

Cloud functions use the Admin SDK which bypasses security rules as it's a trusted environment. 
The rules are applied to requests coming from the Web SDK.

So for cloud functions the rules don't apply
For web requests the rules do apply

2022-12-02 16:10 UTC, tomlovesgithub approved these changes

2022-12-04 10:41 UTC, warrensearle approved these changes
Great, thank you 👍

2022-12-14 09:06 UTC, merged