other downloads added back
jac-uk/admin pull request #1795
Opened 2022-11-09 17:10 UTC by tomlovesgithub

## What's included?
'Other Downloads' were missing from the additional content section of the vacancy details page. 
I have re-added them so that uploaded files can be accessed by candidates. 
This PR makes these downloads more visible on the admin platform

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Upload a document (or multiple) under 'other downloads' [admin side]
- Check the file appears, named correctly and downloadable on the apply side 

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.
APPLY >>>
![Screenshot 2022-11-09 at 17 01 35](https://user-images.githubusercontent.com/44227249/200893898-7f25d9cc-9e57-41d9-ae04-2fdba4b217f1.png)

![image](https://user-images.githubusercontent.com/44227249/200895213-dcc989e1-ab97-4e1c-9c8f-392e4026989c.png)

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-11-10 09:07 UTC, HalcyonJAC approved these changes
👍

2022-11-17 11:31 UTC, andrew-isaac requested changes
Does not work for me - I added the document on admin under exercise downloads in the other section but this does not show on the apply side.

2022-11-30 19:17 UTC, andrew-isaac commented
@tomlovesgithub  - Can update this ticket please

2022-12-01 20:58 UTC, warrensearle submitted a review, later dismissed
One wafffer-thin change please @tomlovesgithub 😄

2022-12-01 20:58 UTC, warrensearle commented on src/views/Exercise/Details/Downloads/View.vue
> +          </ul>
Can you switch this around to include `v-if="showOtherDownloads"` on the `<ul>` tag and follow this with `v-else` on the `No files uploaded` message.

Right now when there aren't any files we'll have an empty `<ul>` tag

2022-12-14 11:29 UTC, warrensearle approved these changes
👍

2022-12-22 13:04 UTC, merged