#1836 Statutory Consultation Report
jac-uk/admin pull request #1843
Opened 2023-01-10 12:57 UTC by HalcyonJAC

## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-01-16 09:42 UTC, warrensearle approved these changes
This looks good although I would have thought the report would be shown on screen too

2023-01-16 15:53 UTC, andrew-isaac requested changes
I tried other exercises on staging with candidates in various stages/stages but couldn't get the export data button to work. I refreshed the page after changing candidates stage/status but the export data button was still greyed out?  Am I doing something wrong :)  - It worked only for me on 502 which is in the video.

2023-01-17 09:24 UTC, HalcyonJAC commented
@andrew-isaac I deployed the cloud function again and it should work now. Could you test it again, please?

2023-01-17 11:17 UTC, andrew-isaac approved these changes

2023-01-17 14:29 UTC, tomlovesgithub approved these changes

2023-01-17 14:32 UTC, merged