1855/pagination toggle
jac-uk/admin pull request #1856
Opened 2023-01-19 17:17 UTC by tomlovesgithub

## What's included?
Toggle button for pagination on application lists; withdrawn, draft and applied, switches between 'old' previous/next pagination, and alphabetical pagination. 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
 - visit the withdrawn, draft and applied list pages
 - toggle pagination type
 - test pagination functionality.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
![image](https://user-images.githubusercontent.com/44227249/213513685-068d43a4-e681-4430-8b13-7bfd59ff8434.png)
![image](https://user-images.githubusercontent.com/44227249/213513758-87ce01b9-bb46-4fa4-b3cd-7cba500bd1c3.png)

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-01-19 18:02 UTC, tomlovesgithub commented
muted a failing test suite so i can get the preview url up and running, will not merge this branch until the suite is fixed

2023-01-19 18:06 UTC, andrew-isaac approved these changes

2023-01-24 10:38 UTC, warrensearle requested changes
Looks good though should probably:
 - add a little bit of spacing between Next/Prev buttons and the toggle button
 - have the toggle button as a secondary button (i.e. not green) as we should ideally have only one, or just a few, primary call to actions per screen
 - make the default Prev/Next pagination
<img width="150" alt="image" src="https://user-images.githubusercontent.com/8524401/214269412-81b8fb39-227f-4d00-a125-b2b65714d6cb.png">

2023-01-30 17:34 UTC, warrensearle approved these changes

2023-02-01 14:43 UTC, merged