1776/agency report barrister
jac-uk/admin pull request #1915
Opened 2023-02-23 18:04 UTC by tomlovesgithub

## What's included?
this includes all candidates who have declared barrister experience in the BSB report, both on the admin site, and in the download.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
**- Will be very hard to find an exercise to test this against on develop**

- Find exercise with agency report
- Under BSB ensure all candidates who have selected yes to barrister appear.

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-02-27 10:17 UTC, HalcyonJAC reviewed
Now on apply we collect the date a candidate called to the Bar and store it in the field `calledToBarDate`. But the `bsbDate` will be populated from the field `date` on digital-platform. Not sure which field we should use to show in the BSB table.
@tomlovesgithub,  could you double-check it, please?

2023-02-28 10:07 UTC, warrensearle requested changes
One small tweak needed 😄

2023-02-28 10:07 UTC, warrensearle commented on src/views/Exercise/Reports/Agency.vue
> +                    {{ 'None given' }}
😄 Do you need the double braces?

2023-03-02 13:08 UTC, andrew-isaac approved these changes

2023-03-03 09:19 UTC, warrensearle approved these changes
👍

2023-03-22 09:41 UTC, merged