#1861 Processing applications
jac-uk/admin pull request #1931
Opened 2023-03-14 17:28 UTC by warrensearle

## What's included?
Quite a few changes to support the processing of applications.

In particular MVP support for:
- Sift
- Telephone assessment
- Other shortlisting methods
- Custom marking schemes
- Stage outcome
- Selection day

Closes #1866 
Closes #1867 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Set up or locate an exercise with applications and try to run any or all of the following:

- Sift
- Telephone assessment
- Other shortlisting methods
- Custom marking schemes
- Stage outcome
- Selection day

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes a lot of changes to shared code

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-03-15 14:19 UTC, andrew-isaac approved these changes

2023-06-28 12:54 UTC, tomlovesgithub approved these changes

2023-07-11 11:03 UTC, HalcyonJAC requested changes
It seems that the page size doesn't work. When I change the page size to 10, it shows more than 10 records in the table. Here is the video:

https://github.com/jac-uk/admin/assets/79906532/f26223cb-eebc-4ab4-adb2-1bb7da48bd6a

2023-07-11 11:11 UTC, warrensearle commented
> It seems that the page size doesn't work.

Thanks Ryan. Turns out this is quite an old PR now and lots of changes have happened in the last 4 months! I'll get it refreshed and merge conflicts sorted then re-request a review.

2023-10-03 12:03 UTC, drieJAC approved these changes

2023-10-03 15:37 UTC, tomlovesgithub approved these changes

2023-10-04 09:56 UTC, HalcyonJAC approved these changes

2023-10-05 11:48 UTC, merged