#1841 Select applications for character checks by application status
jac-uk/admin pull request #1935
Opened 2023-03-16 18:20 UTC by tomlovesgithub

## What's included?
Adds dropdown selections for `stage` and `status`.
Using `availableStatuses` so should slot in and be improved by [this pr](https://github.com/jac-uk/admin/pull/1931).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Navigate to an exercise with character checks 
- Check the available stages and status work to filter the table contents
- find any flaws or issues within this

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
![image](https://user-images.githubusercontent.com/44227249/225716294-e1563fd0-d856-4c86-9709-1e35d184a1ea.png)

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-03-17 13:20 UTC, andrew-isaac approved these changes

2023-03-20 09:08 UTC, HalcyonJAC requested changes

2023-03-24 09:23 UTC, HalcyonJAC requested changes
When I select the status `Invited To selection`, it shows blank and the data in the table seems not correct.

https://user-images.githubusercontent.com/79906532/227477405-fed6e1b5-8e4f-4fb4-91bd-d6756ee8b7ee.mov

2023-03-30 09:42 UTC, warrensearle approved these changes
Code looks good. I think this needs #1861 to be merged first though, is that right @tomlovesgithub?

2023-11-21 00:31 UTC, drieJAC approved these changes

2024-08-23 09:38 UTC, closed without merging