#1709 admin main page improvements
jac-uk/admin pull request #1936
Opened 2023-03-17 11:15 UTC by HalcyonJAC

## What's included?
Closes #1709 

Design: https://www.figma.com/file/pR7HqskdIISgNGEw2SAZJC/1709-Admin-UI-Main-Page-Improvements?node-id=0-1&t=RYDrzbAY1mLelbD4-0

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-03-24 12:00 UTC, andrew-isaac approved these changes

2023-03-29 12:46 UTC, tomlovesgithub approved these changes

2023-03-30 10:05 UTC, warrensearle requested changes
Hey @HalcyonJAC I like the larger blue bar and the 4 items showing in the timeline however there are a couple of things to address:

1. The timeline should show the latest / most relevant timeline events. Currently it is static and always shows the Open and Closed dates even if an exercise is at the end of it's timeline

2. The existing approval modal appears to have been replaced. Please change the text back to what we had before:

**Before**
<img width="753" alt="image" src="https://user-images.githubusercontent.com/8524401/228798551-4e1e529a-bf39-485d-bc4f-74256dccaab0.png">

**After**
<img width="768" alt="image" src="https://user-images.githubusercontent.com/8524401/228798702-e91539e6-cd83-45d8-9f57-61255a64a4bb.png">

3. Please try to use `govuk` classes rather than inline CSS

2023-03-30 10:05 UTC, warrensearle commented on src/views/Exercise/Details/Overview/ApproveReject.vue
> +      <div style="padding-left: 45px;">
Please use govuk classes rather than inline styles

2023-03-30 10:05 UTC, warrensearle commented on src/components/ModalViews/ExercisePreApprovalTaskList.vue
> +          <li>Number fifth</li>
Please change text back to what we had before.

2023-04-05 09:45 UTC, warrensearle approved these changes
👍

2023-04-12 08:44 UTC, merged