Feature/2005  User Management - Functionality Improvements
jac-uk/admin pull request #2054
Opened 2023-07-07 08:16 UTC by HalcyonJAC

## What's included?
Closes #2005 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-08-11 12:04 UTC, warrensearle requested changes
I have a few questions/changes. Let's go through this via DM 😄

2023-08-11 12:04 UTC, warrensearle commented on src/main.js
> +      isAuth = true;
Let's discuss. We need to always be using the auth token / custom claims rather than what is in the `users` document

2023-08-30 12:58 UTC, warrensearle requested changes
All looks great, just one thing to check (see comment)

2023-08-30 12:58 UTC, warrensearle commented on src/store/users.js
> +    },
As discussed please check if this is still needed 😄

2023-08-30 16:09 UTC, NormaJAC reviewed
ok

2023-08-31 09:10 UTC, warrensearle approved these changes
Code looks great 👍 
Have I mentioned before how good it is to get rid of the cloud function that was being called upon login (the one that meant the UI took ~10 seconds to load) 😃

2023-09-01 10:46 UTC, nickaddy commented
@tomlovesgithub @warrensearle I cannot see Users or Roles on Admin, is this a permissions matter? Help!

2023-09-01 10:59 UTC, warrensearle commented
> @tomlovesgithub @warrensearle I cannot see Users or Roles on Admin, is this a permissions matter? Help!

Yes, sounds like a permissions matter. Will check and DM you

2023-09-01 11:11 UTC, nickaddy commented
@HalcyonJAC I cannot see Users/roles on Develop or Production Admin whether logged in with .gov.uk or .digital address, could you have a look at my permissions pls?

2023-09-01 11:52 UTC, warrensearle commented
Hey @HalcyonJAC @nickaddy I just checked our code and Nick would need to be added to the following file:

`src/helpers/authUsers.js`

However could we take the opportunity here to ensure that this is removed from our code base. The Users link showing, or not, should be dependent upon the current user having the correct user role/permission.
We need to get rid of the hard-coded email addresses 🤓

2023-09-08 11:07 UTC, HalcyonJAC commented
> Hey @HalcyonJAC @nickaddy I just checked our code and Nick would need to be added to the following file:
> 
> `src/helpers/authUsers.js`
> 
> However could we take the opportunity here to ensure that this is removed from our code base. The Users link showing, or not, should be dependent upon the current user having the correct user role/permission. We need to get rid of the hard-coded email addresses 🤓

@warrensearle The hard-coded email addresses have been removed. Could you re-review it, please?

2023-09-15 14:18 UTC, warrensearle approved these changes
Looks good to me. Just the `UserInvitations` change to include

2023-09-15 15:41 UTC, tomlovesgithub approved these changes

2023-10-19 11:29 UTC, nickaddy requested changes
Great to see this feature taking shape! I can see the Users tab now 😊

Users
I can’t confirm all users are listed but I did some random searches and Sophie Austin does not appear to be included – this will need a full audit
Search functionality generally works but when I enter ‘addy’ there are no results returned, when I enter ‘nick’ I get both my entries and one for another Nick, in other words, as a search term, Nick works but not Addy
Pagination works, but the first time I went in, there was a previous button on the first page which took me to an error page
When I click Disable, it changes to Enable and vice versa
I tried to delete Abdalla bidu digital address, received an are you sure pop-up and successfully deleted him (at least the entry disappeared from the list)
I was able to change the role of a user

Roles
I can see all roles
I was able to change permissions of several roles
Able to create a new role, but once I click on Save and Set permissions, screen defaults to the role I was on when I pressed the ‘create a new role’ button rather than the new role
I was able to set permissions on the new role

User Invitations
I have created an invitation (Zubair Ali) but not sure how to test this using MS login?


Question:
Is there a reason why .gov.uk accounts names appear surname, firstname and .digital appear firstname surname?

2023-11-03 15:17 UTC, HalcyonJAC commented
Roles
- The screen will now load the new role if you just create a new one.

User Invitations
- I have created an invitation (Zubair Ali) but not sure how to test this using MS login?
    Ans: Would it be possible to get a Microsoft account? 

Question:
- Is there a reason why .gov.uk accounts names appear surname, firstname and .digital appear firstname surname?
    Ans: I just populate the display name from their Microsoft/Google account when they log in. I am not sure if I could change their name.

2023-11-03 15:21 UTC, nickaddy commented
@HalcyonJAC Thanks for the updates. There are some other associated tasks before we can go live with this - I'll pick them up once I'm back from leave.

2023-11-21 00:30 UTC, drieJAC approved these changes

2023-12-14 11:45 UTC, nickaddy approved these changes

2023-12-14 11:46 UTC, merged