Feature/2092 Exercise contacts - Assigned commissioner field
jac-uk/admin pull request #2093
Opened 2023-08-01 14:45 UTC by HalcyonJAC

## What's included?
Closes #2092 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-08-01 16:32 UTC, warrensearle requested changes
One small tweak otherwise looking good 😄

2023-08-01 16:32 UTC, warrensearle commented on src/components/RepeatableFields/AssignedCommissioner.vue
> +      return emails.map(e => e).sort((a, b) => {
Is the `.map(e => e)` doing anything here? Looks like it could be removed

2023-08-01 16:52 UTC, HalcyonJAC commented on src/components/RepeatableFields/AssignedCommissioner.vue
> +      return emails.map(e => e).sort((a, b) => {
Yes, it will create a copy of an array here. The `sort` method will change the original array in place but `this.$store.getters['services/getEmails']('commissioners')` is immutable.

2023-08-02 09:56 UTC, warrensearle approved these changes
Great, looks good to me 😄

2023-08-02 09:57 UTC, warrensearle commented on src/components/RepeatableFields/AssignedCommissioner.vue
> +      return emails.map(e => e).sort((a, b) => {
Cool, thanks @HalcyonJAC

2023-08-11 09:58 UTC, drieJAC approved these changes

2023-08-16 08:52 UTC, merged

2023-08-22 12:42 UTC, nickaddy commented
@HalcyonJAC @warrensearle Just a thought: if there is a new assigned commissioner, how and where are they added to the dropdown?

2023-08-22 12:52 UTC, HalcyonJAC commented
@nickaddy now we store the email addresses of assigned commissioners in the Firestore and it will be populated into the dropdown. We can add new email addresses using Firebase Console. I am happy to do that if there are new email addresses that need to add in.

2023-08-22 13:53 UTC, nickaddy commented
Thanks @HalcyonJAC. I believe there will be a new batch coming up soon as some contracts are coming to an end. Probably, we will be informed of the new ones and we can then add them to the list as you have suggested.