#2095 issue ticketing system
jac-uk/admin pull request #2117
Opened 2023-08-29 11:54 UTC by drieJAC

## What's included?
**This is an initial prototype intended for an initial discussion on the features.**
The features are based on Tom's Miro: https://miro.com/app/board/uXjVMvZy_gs=/
Added a tab to the top right of the screen which will appear on all pages
When you click the tab a form will appear in a modal with some fields completed.
The user can specify how they would like to be contacted. If they choose 'email' then their email address will be prefilled.

Closes #2095 

## Who should test?
✅ Product owner

## How to test?
Go to any page and click the feedback link in the top right hand corner.
View the fields that are present and give your feedback to the team.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
See screenshot:

<img width="1726" alt="Screenshot 2023-08-29 at 12 54 03" src="https://github.com/jac-uk/admin/assets/115651787/3b538aa3-1f7e-4848-9f69-de7cf8f50d4a">

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-08-31 15:39 UTC, nickaddy commented
@HalcyonJAC Thanks for putting together the prototype, Omar. We gathered some internal feedback at the sprint planning meetings and it's shared on [this Miro board](https://miro.com/app/board/uXjVMp_sMWo=/?share_link_id=566904512024).

2023-09-11 09:41 UTC, tomlovesgithub approved these changes

2023-09-11 10:09 UTC, HalcyonJAC requested changes

2023-09-11 10:09 UTC, HalcyonJAC commented on src/components/Feedback/FeedbackForm.vue
> +        types="fileTypes"
I guess here it should use `:types="fileTypes"` to pass the variable into the component.

2023-09-18 10:25 UTC, HalcyonJAC approved these changes
The "Raise A Support Issue With This Page" button will overlap other buttons on a small screen. Not sure if we need to fix it in this PR as it's a prototype now so I just pointed this issue out.

![image](https://github.com/jac-uk/admin/assets/79906532/094656c7-7bce-4a37-9f57-049cd646b46c)

2023-09-18 14:55 UTC, nickaddy commented
User feedback was positive, but issues with uploading files. Could we consider a V2 that permits users submitting a screengrab as they currently do via Slack? If this is going to be very complicated, we might just drop the idea as all the other info we have captured may replace the screengrab?

2023-09-18 14:57 UTC, nickaddy commented
@drieJAC @warrensearle Other comment around button placement overlapping with other text on screen.

2023-09-27 14:10 UTC, nickaddy commented
@drieJAC @warrensearle Warren and I realised this needs a bit of a tweak earlier - to cater for cases where a user is raising an issue for an applicant. Hence we may need a multi-modal/adaptive modal approach. The first question would be: Are you raising this issue for yourself or an applicant? 

Option 1: Myself > present the options in your current modal
Option 2: Applicant > present the questions below

Name of applicant, Browser type, etc, the usual questions in addition to the 2/3 we have on the current modal, probably without the screenshot option as they won't be able to do one on behalf of the applicant. Perhaps we should add guidance to the user to ensure they are on the relevant exercise page before raising the issue?

Does that make sense?

Longer term, this feature may be rolled out to the apply side, but in the the meantime, users need a mechanism for raising candidate issues.

2023-10-04 16:30 UTC, drieJAC commented
Ok @nickaddy @warrensearle those changes have been done

2023-10-05 08:51 UTC, nickaddy commented
@drieJAC @warrensearle Love what you've done with this Omar :-) I have a couple of comments:

- Notice you've changed the format of the raise an issue button (in relation to display overlap issues?), if we're going with an icon, could it be sthg a bit more obvious like, e.g. a red exclamation mark? Whatever we choose, I suppose SETs will soon get familiar with.
- On the raising for someone else form, I wonder if we should add sthg about issues on CPS devices or maybe that is sthg that is communicated separately to SETs as a first step? Open to suggestions...

Anyway, let's put it back to UT next week :-)

2023-10-05 10:10 UTC, warrensearle commented
Looks like the message to "Please ensure you are on the relevant page..." is on the wrong page. It should go with the capture screenshot functionality shouldn't it?

<img width="609" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/0daeccf3-88f3-45a8-abf7-fb3736a46e4e">

2023-10-05 10:13 UTC, warrensearle commented
When gathering data from the applicant we should ask for the URL of the page the applicant has a problem with.

Perhaps we should also refer to them as "candidate" rather than "applicant". Both are correct but the tendency is to call them candidates

2023-10-05 10:14 UTC, nickaddy commented
@warrensearle This was so we could capture the exercise details that the candidate was involved in, rather than having to ask them to submit a url. It could also be mentioned on the 'myself' form.

2023-10-05 10:48 UTC, warrensearle commented
Ah right so we need to make the following changes:

- [ ] Change "Applicant" to "Candidate"
- [ ] Change the warning when raising an issue for a candidate application to "Please ensure you are on the relevant candidate application page before raising the issue"
- [ ] When raising an issue for a candidate include a prompt to ask "Have you checked if the candidate is using a CPS device?"
- [ ] Include a warning when raising an issue for myself to say "Please ensure you are on the relevant page before raising the issue"

2023-10-05 10:56 UTC, warrensearle requested changes
Please see comments

2023-10-24 13:04 UTC, drieJAC commented
Add a link to the screenshot to the issue in Zenhub and a link to the Zenhub issue in Slack

2023-10-26 11:07 UTC, nickaddy requested changes
Partly successful: ticket created in ZenHub and data passed to Firestore collection, but content of user-completed fields was truncated (I specifically added a lot of text to test this). Screenshot also needs to be linked to in ZH ticket (Omar aware.)

2023-10-26 11:15 UTC, nickaddy commented
@drieJAC I should have added that it all works for candidates too

2023-10-26 11:17 UTC, nickaddy commented
@drieJAC to discuss at this week's Devs meeting which additional data, e.g. OS, browser, user email should be passed to the ZenHub ticket.

Additional request: can 'myself' issues be auto-allocated a 'User' label in ZH and 'candidate' issues be allocated a 'Candidate' label in ZH.

2023-10-26 14:36 UTC, nickaddy commented
@drieJAC What did you expect to happen user input needs to be passed to ZH/Slack

2023-11-01 15:49 UTC, nickaddy commented
@drieJAC Can we automate a label 'apply' or 'admin' to the ticket according to whether ticket is candidate or user related?

2023-11-01 15:52 UTC, nickaddy commented
@drieJAC When ticket assigned in ZH, send notification to developer assigned in Slack channel.

2023-11-01 15:53 UTC, nickaddy commented
@drieJAC when issue is resolved, user is notified.

2023-11-01 17:13 UTC, nickaddy commented
@drieJAC @warrensearle I have created a [messages section](https://miro.com/app/board/uXjVMgsSPkg=/?moveToWidget=3458764568633829550&cot=14) on the Miro board.

2023-11-01 17:23 UTC, nickaddy commented
Otherwise, Omar & I agreed it is OK for additional conversation to take place in digital issues Slack channel thread if required with developer pasting anything pertinent into the ZH ticket.

Suggest a live UT session later in the month, where users raise issues and we triage them live.

2023-11-02 13:24 UTC, nickaddy commented
@drieJAC @warrensearle Just had a thought: if we are passing the assignee back to the reporter, we need to either make aliases for our usernames in GH/ZH or change our usernames to reflect at least our first names. Thoughts?

2023-11-02 13:56 UTC, nickaddy commented
@drieJAC @warrensearle Sorry about the multiple messages - I was hoping we would catch up today but with Warren still in the Canaries, that's not going to happen. We are going to need to link this board to a GH repo: 1) for automations, 2) for metrics.

2023-11-20 10:36 UTC, drieJAC commented
Investigate...

- Add label to zenhub issue.
- Send emails on change of status.

2023-11-21 15:44 UTC, nickaddy commented
@warrensearle Modal is generating an error today - not sure if Omar made changes yesterday - oddly, it does actually send to Slack and ZH, but not all of the data.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGYyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7612a1b9d16ca549ffb5f6ae6cdc1c39b54d25dc/image.png)

2023-12-15 16:46 UTC, merged