Feature/2097 outreach report
jac-uk/admin pull request #2137
Opened 2023-09-20 08:42 UTC by drieJAC

## What's included?

**Only Sean Cuddihy needs to test this!**

We currently ask candidates the following questions when applying:

-  where they heard about the role
- have they attended an outreach event on JAC selection exercises
- did they participate in a Judicial Workshadowing Scheme
- have they taken part in the Pre-Application Judicial Education Programme (PAJE)

The outreach report collates the figures for the answers to these questions.

Closes #2097 

## Who should test?
Sean Cuddihy

## How to test?
Go to the Outreach Report and ensure the report numbers accurately reflect the answers from the applications.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-09-21 09:27 UTC, nickaddy commented
It would be beneficial to have all of this information in one place and to, therefore, add the additional fields from the diversity monitoring form to the outreach report on the platform.

In addition, the declaration rate on the report is currently listed amongst the outreach options. At the top of the report is a grey box showing the 'Total applications'. Could the grey box also include the declaration rate?

2023-09-25 08:16 UTC, warrensearle requested changes

2023-09-25 08:16 UTC, warrensearle commented on src/views/Exercise/Reports/Outreach.vue
> +                <Stat :stat="report[activeTab].outreach['judging-your-future-newsletter']" />
Do we _need_ to hardcode this? Looks like it was dynamic previously and now has been changed to be hardcoded. Please double check

2023-09-25 11:55 UTC, drieJAC commented on src/views/Exercise/Reports/Outreach.vue
> +                <Stat :stat="report[activeTab].outreach['judging-your-future-newsletter']" />
Done

2023-09-26 11:34 UTC, drieJAC commented
Feedback from Sean Cuddihy:

On the production link in your email (https://jac-apply-admin-production--2097-outreach-j3l1v5bc.web.app/) some exercises seemed to be working (00129 worked after I pressed refresh), but 00162 gave an error after I pressed refresh (see screenshot) and I tried an older archived exercise 00115 and that didn't have a refresh button at all.

2023-09-26 11:35 UTC, drieJAC commented
So there was a memory issue with 00162. We have increased the memory and I was able to hit the refresh button fine. That exercise has under 2000 applications and we are ideally supporting 5000 so we are going to do some work to make the memory usage more efficient
Regarding the missing Refresh button for 00115 I didn't see this. I was able to press the button and the numbers got generated ok
I'll make changes to the PAJE question so that the 'online only' and 'judge-led' are displayed and i'll give you a shout as soon as that's done

2023-10-04 15:52 UTC, tomlovesgithub approved these changes

2023-10-05 08:00 UTC, HalcyonJAC approved these changes

2023-10-06 17:13 UTC, merged