#2127 Search Improvements Help Panel
jac-uk/admin pull request #2139
Opened 2023-09-25 00:11 UTC by drieJAC

## What's included?
Added help panel for search.
Updated empty search results panel.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Ensure the following searches work correctly and display the correct information in the help box.

- Exercises Search
- Candidates Search
- Applications Search
- Independent Assessments Search
- Character Checks Search

See the screen recording below as an example of the Exercises Search.

https://github.com/jac-uk/admin/assets/115651787/bb033c83-57a7-4484-8715-407c2bde5087

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
<img width="1204" alt="266007148-3572f595-b89c-44de-983f-84d0b61f03af" src="https://github.com/jac-uk/admin/assets/115651787/82eb82e0-3b10-4f30-9d41-d00d47c5fe24">

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-09-25 08:59 UTC, warrensearle requested changes

2023-09-25 08:59 UTC, warrensearle commented on src/mixins/searchMixin.js
> +export default searchMixin;
Is this being used anywhere in Admin?

2023-10-03 09:37 UTC, warrensearle approved these changes
👍

2023-10-04 10:06 UTC, HalcyonJAC requested changes
I found a tiny issue. Please see the screen record. It seems that it will only happen when there is only one record in the table.

Example exercise: https://jac-admin-develop--pr2139-feature-2127-search-ug76l1oz.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/applications/withdrawn

https://github.com/jac-uk/admin/assets/79906532/4718588c-b0ba-4c97-9233-ec61e7ba9b0e

2023-10-09 09:43 UTC, tomlovesgithub approved these changes

2023-10-10 10:32 UTC, drieJAC commented
@warrensearle has said to ignore the small display bug that @HalcyonJAC reported above as in a future iteration we will modify the help panel so that it will appear above/below/left/right of the help button based on whether there is sufficient space on the screen. In doing so it will fix this bug.

2023-10-10 10:38 UTC, merged