Feature/2143 capture commissioner conflicts
jac-uk/admin pull request #2179
Opened 2023-10-18 10:46 UTC by HalcyonJAC

## What's included?
Closes #2143 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-10-20 17:02 UTC, Franceswog reviewed
Yes, the report was exported to google drive .

2023-10-20 17:25 UTC, nickaddy requested changes
I could not see any conflicts in the table. When I clicked the export button, it whirred and said 'Success' but no report was downloaded.

2023-10-23 09:27 UTC, HalcyonJAC commented
> I could not see any conflicts in the table. When I clicked the export button, it whirred and said 'Success' but no report was downloaded.

@nickaddy I have created some dummy data for testing. The report will be saved to Google Drive or you can download it from the UI.

2023-10-24 07:27 UTC, nickaddy approved these changes
Works as described: word documents downloads to local drive, all stated conflicts presented on separate rows in word document.

2023-11-21 00:29 UTC, drieJAC approved these changes

2023-11-21 09:06 UTC, merged