#2167 Update Application view
jac-uk/admin pull request #2213
Opened 2023-11-03 14:31 UTC by HalcyonJAC

## What's included?
Closes #2167 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Example exercise:
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft

Example application:
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/GYLBhVPwiNflRTpAGfrM
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/NOmunes43iHwX7AdxAZN
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/LinokWzjBmo6uNykztEa

Steps:
1. Go to an application.
2. Check if you can amend the "Post-qualification experience".
    When "The carrying-out of judicial functions of any court or tribunal" is ticked, check if you can amend:
    - Is this a judicial or quasi-judicial post?
    - How many sitting days have you accumulated in this post?
    - Is a legal qualification a requisite for appointment?
    - The powers, procedures and main responsibilities (quasi-judicial only) 
    - Details of how you have acquired the necessary skills
 
3. Check if you can amend the "Gaps in employment".

![image](https://github.com/jac-uk/admin/assets/79906532/19e41174-57c3-4305-bedc-bc30c0a4ecb9)

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/jac-uk/admin/assets/79906532/b9c41066-1eee-402f-abf1-585782d9d526

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2023-11-20 08:31 UTC, nickaddy approved these changes

2023-11-21 00:28 UTC, drieJAC approved these changes

2023-11-21 10:26 UTC, warrensearle requested changes
One small suggestion otherwise code looks good

2023-11-21 10:26 UTC, warrensearle commented on src/views/InformationReview/ExperienceSummary.vue
> +    isApplicationVersion3() {
This needs to be 'future proof' so when application version 4 or greater comes out the code still works as expected.

i.e. the version 3 code should display for version 4 and later until those versions introduce a change

As it stands currently the version 2 code will display for version 2 or less and for version 4 or higher.

The code itself could use `this.exercise._applicationVersion >== 3` instead of `this.exercise._applicationVersion === 3` and the function named `isApplicationVersion3OrMore` or perhaps use methods along the lines of `isApplicationVersionGreaterThan(2)` and/or `isApplicationVersionLessThan(3)`

2023-11-21 15:09 UTC, warrensearle approved these changes
Great, thank you 👍

2023-11-21 15:33 UTC, merged