1072/location prefs
jac-uk/admin pull request #2340
Opened 2024-03-01 17:33 UTC by tomlovesgithub

2024-03-05 12:43 UTC, Franceswog approved these changes
On Exercise- questions, answers, and type all displayed correctly
On Application review, questions, answers - I could edit and save

2024-03-12 09:14 UTC, HalcyonJAC requested changes
Could you resolve the merge conflicts, please?

2024-03-19 23:09 UTC, drieJAC approved these changes

2024-03-26 09:43 UTC, HalcyonJAC approved these changes

2024-04-02 11:26 UTC, warrensearle commented
Some tasks to address:

 - [ ] View single choice question. Should not display non-relevant config - e.g. I changed a question from multiple choice, two answer minimum to single choice and the text "2 answer minimum" is still displayed. See image below:
<img width="868" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/8a98559c-529f-4777-94dd-2142220863c2">

 - [ ]

2024-04-11 09:03 UTC, merged