Bugfix/2345 Character issues from previous applications are not appearing
jac-uk/admin pull request #2358
Opened 2024-03-21 09:16 UTC by HalcyonJAC

## What's included?
Closes #2345 

- Fix Firebase modular syntax.

## Who should test?
✅ Product owner
✅ Developers

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-03-21 10:08 UTC, NormaJAC approved these changes

2024-03-25 08:39 UTC, nickaddy requested changes
@HalcyonJAC I edited the data on this candidate's application for JAC00685 and JAC00636, but when I refresh the character page, they do not appear and the test does not change from 'Data not requested.' What is the trigger for that text?

2024-03-25 14:06 UTC, warrensearle approved these changes

2024-03-26 09:03 UTC, HalcyonJAC commented
@nickaddy I have fixed the test data and the historical character issues for JAC00685 and JAC00636 are appearing. "Data not requested" is triggered when there are no character issues from the application.

2024-03-27 08:39 UTC, nickaddy commented
@HalcyonJAC Looking at a live exercise, A***** A****** declared the same issues on his application for JAC00077, but they do not appear when you click on [View all character issues from previous applications](https://admin.judicialappointments.digital/exercise/HdvJaVf4QIpGTDJDmeYz/reports/character-issues#). Even if they are the same ones, anything that has been declared on a previous exercise should appear when `View all character issues from previous applications` is clicked.

2024-04-03 11:00 UTC, merged