filter JCIO applications
jac-uk/admin pull request #2366
Opened 2024-04-08 16:09 UTC by KoWeiJAC

## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

closes #2290 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link:
- Check if applications needs JCIO are listed in the JCIO report

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-04-11 11:33 UTC, nickaddy requested changes
@KoWeiJAC Perhaps my review should be on the other PR, because the Admin view is displaying correctly, but the download shows both applications whereas it should only show the one that is shown onscreen, i.e. the one that has ticked the 'carrying out of judicial functions' tickbox.

2024-04-15 06:56 UTC, nickaddy approved these changes
Looking good @KoWeiJAC 👍

2024-04-18 08:55 UTC, warrensearle approved these changes

2024-04-29 08:07 UTC, HalcyonJAC approved these changes

2024-04-29 08:08 UTC, merged