fix other applications not show
jac-uk/admin pull request #2374
Opened 2024-04-17 09:29 UTC by KoWeiJAC

## What's included?
closes #2373 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link:
- Click `View all reasonable adjustments`, it should work

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-04-17 09:56 UTC, nickaddy requested changes
@KoWeiJAC I guess this was not the original bug, but could you change the headings underneath the previous adjustments: Reason >  RA applies to AND Note > RA allocated

![image](https://github.com/jac-uk/admin/assets/138654969/5a296624-567b-4b24-bfdb-5eaefe130a3e)

2024-04-17 11:08 UTC, KoWeiJAC commented
> * https://jac-admin-develop--pr2374-bugfix-admin-2373-re-4uuexxxo.web.app/exercise/X2tDg5AKt18xvzBRJFYW/reports/reasonable-adjustments

@nickaddy 
The headings have been changed, could you help me to check ? Thanks

2024-04-18 08:48 UTC, warrensearle approved these changes

2024-04-18 10:05 UTC, Franceswog approved these changes

2024-04-18 21:26 UTC, HalcyonJAC approved these changes

2024-04-22 16:41 UTC, NormaJAC approved these changes
Headings have changed.

2024-04-23 13:28 UTC, merged