Bugfix/TS 305 Shortlisting Other Statuses
jac-uk/admin pull request #2394
Opened 2024-05-10 11:28 UTC by HalcyonJAC

## What's included?
Closes [User Raised Issue BR_ADMIN_PR_000108 #305](https://github.com/jac-uk/ticketing-system/issues/305)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-05-10 13:05 UTC, nickaddy approved these changes
Looks good, @HalcyonJAC. When this is released and the candidates are progressed to shortlisting stage, will Richard be able to dispatch the character consent request and create the panel packs?

2024-05-13 10:14 UTC, KoWeiJAC approved these changes

2024-05-13 10:41 UTC, warrensearle requested changes
See comment here: https://github.com/jac-uk/ticketing-system/issues/305

I think it would be safer to introduce a new status for exercises with an 'Other' shortlisting method

2024-05-13 14:04 UTC, warrensearle approved these changes

2024-05-13 14:25 UTC, merged