Statuses for withdrawn candidates
jac-uk/admin pull request #2415
Opened 2024-06-03 16:25 UTC by tomlovesgithub

## What's included?
Updates to `store/application.js` so that a check for an accompanying `applicationRecord` can be accessed and used when withdrawing an application from the application view. 
Using this, the button now updates the withdrawn status to both if both exist, if not, only the application status is updated. 

## How to test?
Withdraw an application from an application view. Ensure that the status is updated and reflected in all application lists.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
![image](https://github.com/jac-uk/admin/assets/44227249/febffc89-754f-47c6-b7c1-f17ebad836dd)

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-06-06 09:16 UTC, nickaddy requested changes
@tomlovesgithub The results seem to be patchy - see the candidates under Withdrew on [this exercise](https://admin-develop.judicialappointments.digital/exercise/GYysuH7M4V21MFVM8Dzg/applications/withdrawn). Some have their status correctly populated, others don't. I've tried to isolate whether the unpopulated cases are either from pressing the button or changing the status but there doesn't seem to be any rhyme or reason.

2024-06-07 15:04 UTC, nickaddy commented
Looking good, Mr T! I note there are still a few candidates on 184 with a blank status column. Once you've addressed, I'll be happy to approve the ticket :-)

2024-06-07 15:07 UTC, nickaddy approved these changes

2024-06-07 15:10 UTC, drieJAC approved these changes

2024-06-07 15:21 UTC, HalcyonJAC approved these changes

2024-06-07 16:12 UTC, merged