2422/eligib v2 improve
jac-uk/admin pull request #2426
Opened 2024-06-20 16:20 UTC by tomlovesgithub

## What's included?

- Add a status dropdown filter at the top of the screen
- Only candidates with the selected status should be displayed onscreen
- Only candidates with the selected status in addition to the criteria already set in [#2396](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2396) should be included in the report

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-06-24 13:48 UTC, HalcyonJAC requested changes

2024-06-24 14:26 UTC, nickaddy commented on src/views/Exercise/Reports/EligibilityIssuesV2.vue
> +      applicationStatusOptions: APPLICATION_STATUS,
@tomlovesgithub This meets the request laid out on the ticket, however, I've recently been speaking with Ryan about the character report, which is being used quite early on, before the point at which candidates have any status. I wonder if it might be prudent to include the blank status option in this list in case a similar need arises for users running the eligibility report?

2024-07-01 08:57 UTC, HalcyonJAC approved these changes

2024-07-02 10:25 UTC, nickaddy requested changes
@tomlovesgithub I can see the dropdown now, but when I download the annex, it includes all candidates rather than those filtered by the dropdown. The associated ticket referred to has apparently been released, hence can you look into this further pls?

2024-07-08 08:55 UTC, merged