Make Pagination numerical by default
jac-uk/admin pull request #2454
Opened 2024-06-21 16:01 UTC by tomlovesgithub

## What's included?
do-over of old branch with merge issues.

Alphabetical pagination on the stat-con report page was causing confusion with the stat-con download. 
I have made the pagination numerical by default so this page should always load any results, reducing confusion. 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
visit stat con page (exercise >> reports >> statutory-consultation)
ensure pagination is numerical on initial load.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-06-21 16:12 UTC, drieJAC commented on src/views/Exercise/Reports/StatutoryConsultation.vue
> +      total: null,
maybe best to set this to 0 instead of null

2024-06-21 16:26 UTC, HalcyonJAC requested changes

2024-06-21 16:26 UTC, HalcyonJAC commented on src/views/Exercise/Reports/StatutoryConsultation.vue
> +      const res = await tableAsyncQuery(this.applicationRecords, firestoreRef, params);
Could you pass `null` as the 4th parameter, please? It will be like:
`const res = await tableAsyncQuery(this.applicationRecords, firestoreRef, params, null);`

2024-07-01 08:56 UTC, drieJAC approved these changes

2024-07-08 08:56 UTC, merged