Feature/2429 test navigation improvements
jac-uk/admin pull request #2480
Opened 2024-07-08 08:14 UTC by drieJAC

## What's included?

1. Have the items in the sub-menu display in a grey box underneath the top navigation (see Figure 1 below)
2. Have a grey line delineating which menu items are selected
3. The menu that appears pushes the screen content down

Closes #2429 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Ensure the tab links and sub menu links work
Ensure the correct links are shown for exercises in different states.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Figure 1

<img width="1185" alt="Screenshot 2024-07-08 at 09 12 18" src="https://github.com/jac-uk/admin/assets/115651787/de731f78-2e16-430d-ba4a-0d5afea83d31">

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2024-07-08 09:01 UTC, nickaddy commented
@drieJAC Two questions:
- Is it possible to see this submenu in action?
- Are you content that we will be able to manage the dynamic tasks submenu?

2024-07-08 09:12 UTC, drieJAC commented
@nickaddy I needed to fix something before the preview url was created. That's now fixed so you can use the preview url to view the submenu.
It would be good to check the scenarios under which the submenu items should appear. I expect there will need to be a few changes.

2024-07-08 09:39 UTC, warrensearle commented
Looking good but spotted the following:

- [ ] The up/down arrows need to be reversed. Should be: down arrow (v) when menu is closed and can be opened; up arrow (^) when menu is open and can be closed
- [ ] Link colour should stay as it was (blue for links; black when current) rather than changing to purple (unless I've missed this request)

2024-07-08 09:57 UTC, nickaddy commented
> Looking good but spotted the following:
> 
> * [ ]  The up/down arrows need to be reversed. Should be: down arrow (v) when menu is closed and can be opened; up arrow (^) when menu is open and can be closed
> * [ ]  Link colour should stay as it was (blue for links; black when current) rather than changing to purple (unless I've missed this request)

@drieJAC Agreed. Could you mirror this change on the Live Exercises page pls?

2024-07-08 11:21 UTC, HalcyonJAC requested changes
Code looks good to me.
I spotted something. If I click `Exercise` and then click `Applications`, the submenu will not disappear. Please see the following demo: 

https://github.com/jac-uk/admin/assets/79906532/dd03f824-fe86-47f4-ad7f-c93acb04f549

2024-07-08 11:45 UTC, nickaddy commented
Good spot, @HalcyonJAC - looks like that happens on all menu items except Dashboard...

2024-07-09 13:43 UTC, NormaJAC reviewed
The tab links and sub-menu links work. The sub-menu arrows haven't changed position, still showing up arrow for closed. down arrow for open.

2024-07-25 09:02 UTC, nickaddy commented
@drieJAC Love the new menu! I have a couple of minor requests:

- Pls increase the font size of the reference number to same size as the rest of the text on that row, it's a bit small at the moment, maybe you could make it bold too?
<img width="748" alt="image" src="https://github.com/user-attachments/assets/d2721857-9571-4c0d-9fe7-d8cfe52e7ca2">
- Copy exercise to clipboard is not appearing in the Exercises menu - can you pls add this after Create exercise?

2024-07-29 10:16 UTC, drieJAC commented
@nickaddy 
I've fixed the font-size of the reference number.
The 'copy to clipboard' will only appear if the exercise is approved (and the user has perm to update exercises).
Please confirm this is ok and I'll merge

2024-07-29 11:36 UTC, HalcyonJAC commented on src/views/Exercise/Details.vue
> +  // },
Should we remove the commented code?

2024-07-29 11:36 UTC, HalcyonJAC commented on src/views/Exercise.vue
> +    // },
Should we remove the commented code?

2024-07-29 11:36 UTC, HalcyonJAC commented on src/views/Exercise.vue
> +    // },
Should we remove the commented code?

2024-07-29 12:04 UTC, HalcyonJAC approved these changes
👍

2024-07-29 12:16 UTC, KoWeiJAC approved these changes

2024-07-29 12:20 UTC, merged