Feature/864/qt survey field admin
jac-uk/admin pull request #866
Opened 2020-09-17 12:43 UTC by tomlovesgithub

Add qualifyingTest.feedbackSurvey for feedback form URL
A few Q's on how this is going to be available in the applicant view, and if the url will be copied to the response object or we will have to access the qualifyingTest object directly

2020-09-17 17:55 UTC, lloback requested changes

2020-09-17 17:55 UTC, lloback commented on src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Edit.vue
> +        id="qualifyingTest-testDuration"
@tomlovesgithub you need to change this ID to `qualifyingTest-feedback-survey`.
You can't repeat IDs on the page.

2020-09-18 10:17 UTC, warrensearle requested changes
Please can you add the new field `feedbackSurvey` to the defaults object, with a null value (within the data function)

2020-09-18 10:21 UTC, lloback commented
@tomlovesgithub You have 40 min to get this into the daily release ... no pressure.

2020-09-20 08:41 UTC, lloback approved these changes
ready to go.

2020-09-21 05:18 UTC, lloback commented
> Please can you add the new field `feedbackSurvey` to the defaults object, with a null value (within the data function)

this was done.

2020-09-21 05:18 UTC, merged