Changed data model for invitations
jac-uk/admin pull request #952
Opened 2020-10-13 14:25 UTC by mbrookeswebdev

2020-10-13 21:50 UTC, warrensearle requested changes
Just one change please

2020-10-13 21:50 UTC, warrensearle commented on src/store/invitations.js
> +                invited: serverTimestamp,
`invited` should remain as `null`. It will be set if/when we include sending out email invitations

2020-10-14 08:05 UTC, mbrookeswebdev commented on src/store/invitations.js
> +                invited: serverTimestamp,
Tha't done.

2020-10-14 20:13 UTC, lloback approved these changes

2020-10-14 23:13 UTC, warrensearle approved these changes

2020-10-15 07:21 UTC, merged