Feature/962 withdrawn
jac-uk/admin pull request #964
Opened 2020-10-20 22:28 UTC by lloback

Withdrawn applications should be removed from IAs and QTs

2020-10-21 11:47 UTC, warrensearle requested changes
Few tweaks. See comments

2020-10-21 11:47 UTC, warrensearle commented on src/store/application.js
> +      context.dispatch('assessment/delete', { data: { status: STATUS.DELETED }, id: applicationId }, { root: true });
I think the call to 'assessment/delete' should not include `data`. It should just be the ID to delete. The delete method in that store should take care of implementing what 'delete' means by updating `status` and `statusLog` itself (if that's what it does)

2020-10-21 11:47 UTC, warrensearle commented on src/store/application.js
> +      context.dispatch('qualifyingTestResponses/delete', { data: { status: QUALIFYING_TEST_RESPONSE.STATUS.DELETED }, id: applicationId }, { root: true });
Same as comment about 'assessment/delete'

2020-10-21 11:47 UTC, warrensearle commented on src/store/qualifyingTest/qualifyingTestResponses.js
> +            batch.update(ref, data);
I don't understand this bit. Why is there an update followed by another one (using set)?

2020-10-21 11:47 UTC, warrensearle commented on src/store/stage/review.js
> +          await context.dispatch('application/withdrawn', { applicationId: item }, { root: true });
Being pedantic now but feel this action should be a verb or a more descriptive name.
e.g. `withdraw` rather than `withdrawn`.... or perhaps `withdrawApplication`

2020-10-22 15:40 UTC, lloback commented on src/store/application.js
> +      context.dispatch('assessment/delete', { data: { status: STATUS.DELETED }, id: applicationId }, { root: true });
done.

2020-10-22 15:47 UTC, lloback commented on src/store/application.js
> +      context.dispatch('qualifyingTestResponses/delete', { data: { status: QUALIFYING_TEST_RESPONSE.STATUS.DELETED }, id: applicationId }, { root: true });
done.

2020-10-22 16:01 UTC, lloback commented on src/store/qualifyingTest/qualifyingTestResponses.js
> +            batch.update(ref, data);
Basically, the UPDATE and the SET have different behaviours.
UPDATE, replaces all the object in the database.FOr instance, if I try to update

```
        statusLog: { 
          'deleted': timestamp,
        },
```

All the other children nodes of `statusLog` will be overwritten, so, for example the following would disappear and be replaced by the previous code

```
        statusLog: { 
          'created': timestamp,
          'started' .......
        },
```

On the other hand, SET with the merge flag will keep it.

2020-10-22 16:01 UTC, lloback commented on src/store/qualifyingTest/qualifyingTestResponses.js
> +            batch.update(ref, data);
So, removed the UPDATE and used SET instead.

2020-10-22 16:08 UTC, lloback commented on src/store/stage/review.js
> +          await context.dispatch('application/withdrawn', { applicationId: item }, { root: true });
you know it looks the same to me - so, thanks for pointing out!
Changed.

2020-10-22 16:19 UTC, lloback commented
@warrensearle this is ready for review.

2020-10-22 16:47 UTC, warrensearle commented on src/store/qualifyingTest/qualifyingTestResponses.js
> +            batch.update(ref, data);
Ah right. Did you know you can use dot paths like:
```
data = {
  'statusLog.deleted': timestamp,
};
```
This will leave the rest of `statusLog` object in tact

2020-10-22 16:51 UTC, warrensearle approved these changes
Noice 👍

2020-10-22 17:00 UTC, merged